CREATE FUNCTION FUNC
    RETURN VARCHAR2
    AS
    PROCEDURE LOCAL_PROC(PARAM_OUT IN OUT VARCHAR2);
    PROCEDURE LOCAL_PROC(PARAM_OUT IN OUT VARCHAR2)
        AS
    BEGIN
        NULL;
    END;
BEGIN
    NULL;
END;