CREATE FUNCTION FUNC
    RETURN VARCHAR2
    AS
    FUNCTION LOCAL_FUNC (PARAM_OUT IN OUT NUMBER)
        RETURN VARCHAR2;
    FUNCTION LOCAL_FUNC (PARAM_OUT IN OUT NUMBER)
        RETURN VARCHAR2
    AS BEGIN
        NULL;
    END;
BEGIN
    NULL;
END;