/*[-unconvertible CREATE TYPE t_tf_row AS OBJECT (
  id           NUMBER,
  description  VARCHAR2(50)
)];*/

CREATE GLOBAL TEMPORARY TABLE t_tf_tab (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

/*
CREATE OR ALTER FUNCTION get_tab_ptf (p_rows NUMERIC(34, 8)) RETURNS [-unconvertible t_tf_tab]
[-unconvertible PIPELINED]
SQL SECURITY DEFINER
AS BEGIN
  FOR i IN 1 .. p_rows LOOP
    [-unconvertible PIPE ROW(t_tf_row(i, 'Description for ' || i))];
  END LOOP;

  RETURN 1;
END;
*/