CREATE GLOBAL TEMPORARY TABLE "TEMP_EMPLOYEES"(
    "EMPLOYEE_ID" NUMBER(34,8),
    "FIRST_NAME" VARCHAR2(50 BYTE),
	"LAST_NAME" VARCHAR2(50 BYTE),
	"DEPARTMENT_ID" NUMBER(34,8)
) ON COMMIT DELETE ROWS;