CREATE SEQUENCE NAMES_GENERATOR;

CREATE TABLE NAMES (
    ID INTEGER NOT NULL PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE TRIGGER NAMES_TRIGGER FOR NAMES
    BEFORE INSERT
    SQL SECURITY DEFINER
AS
BEGIN
  NEW.ID = NEXT VALUE FOR NAMES_GENERATOR;
END;

EXECUTE BLOCK
    AS
    /*TYPE Roster IS TABLE OF VARCHAR2(15);*/

    /*names Roster;*/
BEGIN

END: