CREATE FUNCTION F_Open_With_Param
RETURNS VARCHAR(32765)
SQL SECURITY DEFINER
AS
  DECLARE c1_v1 CURSOR FOR (SELECT id FROM test_table WHERE num < 10 AND res = 'OK');
  DECLARE c1_v2 CURSOR FOR (SELECT id FROM test_table WHERE num < 5 AND res = 'POOR');
  DECLARE c1_v3 CURSOR FOR (SELECT id FROM test_table WHERE num < 2 AND res = 'POOR');
  DECLARE c1_v4 CURSOR FOR (SELECT id FROM test_table WHERE num < 3 AND res = 'OK');
BEGIN
  OPEN c1_v1;
  CLOSE c1_v1;
  OPEN c1_v2;
  CLOSE c1_v2;
  OPEN c1_v3;
  CLOSE c1_v3;
  OPEN c1_v4;
  CLOSE c1_v4;
  RETURNS '';
END;