CREATE FUNCTION FUNC
    RETURN VARCHAR2
AS
    FUNCTION LOCAL_FUNC RETURN NUMBER DETERMINISTIC;
    FUNCTION LOCAL_FUNC RETURN NUMBER DETERMINISTIC
        AS
        BEGIN
            NULL;
        END;
BEGIN
    NULL;
END;