CREATE FUNCTION FUNC
    RETURNS VARCHAR(32765)
    SQL SECURITY DEFINER
AS
    DECLARE FUNCTION LOCAL_FUNC RETURNS NUMERIC(34, 8)  DETERMINISTIC;
    DECLARE FUNCTION LOCAL_FUNC RETURNS NUMERIC(34, 8)  DETERMINISTIC
        AS
        BEGIN

        END
BEGIN

END;