CREATE FUNCTION FUNC
    RETURNS VARCHAR
    AS
    DECLARE PROCEDURE LOCAL_FUNC (PARAM_OUT  NUMERIC)
        RETURNS (RET_VAL VARCHAR(32765), PARAM_OUT_OUT NUMERIC(34,8));
    DECLARE PROCEDURE  LOCAL_FUNC (PARAM_OUT  NUMERIC)
        RETURNS (RET_VAL VARCHAR(32765), PARAM_OUT_OUT NUMERIC(34,8))
    AS BEGIN

		PARAM_OUT_OUT = PARAM_OUT;
		SUSPEND;
		EXIT;
    END
BEGIN

END;