CREATE FUNCTION FUNC
    RETURNS VARCHAR
    AS
    DECLARE PROCEDURE LOCAL_PROC (PARAM_OUT VARCHAR)
        RETURNS (PARAM_OUT_OUT VARCHAR(32765));
    DECLARE PROCEDURE LOCAL_PROC (PARAM_OUT VARCHAR)
        RETURNS (PARAM_OUT_OUT VARCHAR(32765))
    AS
    BEGIN

		PARAM_OUT_OUT = PARAM_OUT;
		SUSPEND;
    END
BEGIN

END;