DECLARE
  p1 VARCHAR2(100) := '2 05:30:00';
  res INTERVAL DAY TO SECOND;
BEGIN
  select CAST(p1 AS INTERVAL DAY TO SECOND) into res from dual;
  select CAST(p1 AS INTERVAL DAY TO SECOND DEFAULT NULL ON CONVERSION ERROR) into res from dual;
END;