DECLARE
  p1 VARCHAR2(100) := '3-6';
  res INTERVAL YEAR TO MONTH;
BEGIN
  select CAST(p1 AS INTERVAL YEAR TO MONTH) into res from dual;
  select CAST(p1 AS INTERVAL YEAR TO MONTH DEFAULT NULL ON CONVERSION ERROR) into res from dual;
END;