CREATE GLOBAL TEMPORARY TABLE VEC1_Pack_multiple_PF_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_Pack_multiple_PF_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC1_Pack_multiple_PP_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_Pack_multiple_PP_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_multiple
AS BEGIN
   FUNCTION PF_multiple
   RETURNS VARCHAR(150);
   PROCEDURE PP_multiple; 
END; 

RECREATE PACKAGE BODY Pack_multiple
AS BEGIN
   FUNCTION PF_multiple
   RETURNS VARCHAR(150)
   AS
     /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
     /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
     /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
     /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa VARCHAR(150) = '';
     DECLARE i_FOR1 VARCHAR(15);
  BEGIN
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Olivia');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('William');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Emma');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Henry');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Grace');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('John');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('Mary');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('Alberto');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('Juanita');
     FOR SELECT VAL FROM VEC1_Pack_multiple_PF_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa || i_FOR1; 
     END
     FOR SELECT VAL FROM VEC2_Pack_multiple_PF_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa || i_FOR1; 
     END
     WHILE (1=1) DO
     BEGIN
       i_FOR1 = 'Lily';
       summa = :summa || i_FOR1; 
       LEAVE;
     END
      RETURN 0;
    END

   PROCEDURE PP_multiple
   AS
     /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
     /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
     /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
     /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa VARCHAR(150) = '';
     DECLARE i_FOR1 VARCHAR(15);
  BEGIN
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Olivia');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('William');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Emma');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Henry');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Grace');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('John');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('Mary');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('Alberto');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('Juanita');
     FOR SELECT VAL FROM VEC1_Pack_multiple_PP_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa || i_FOR1; 
     END
     FOR SELECT VAL FROM VEC2_Pack_multiple_PP_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa || i_FOR1; 
     END
     WHILE (1=1) DO
     BEGIN
       i_FOR1 = 'Lily';
       summa = :summa || i_FOR1; 
       LEAVE;
     END
   END
END; 