CREATE PACKAGE CALLING_PACKAGE
AS
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURN VARCHAR2;
END CALLING_PACKAGE;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURN VARCHAR2
   IS
    BEGIN
        PROCEDURE_NAME;
        PROCEDURE_NAME();
    END;
END CALLING_PACKAGE;
---------------------------------------
CREATE PACKAGE CALLING_PACKAGE
AS
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
END CALLING_PACKAGE;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    IS
    BEGIN
        PROCEDURE_NAME;
        PROCEDURE_NAME();
    END;
END CALLING_PACKAGE;