CREATE PACKAGE CALLING_PACKAGE
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURNS VARCHAR(32765);
END /*CALLING_PACKAGE*/;

CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURNS VARCHAR(32765)
   AS
    BEGIN
        EXECUTE PROCEDURE PROCEDURE_NAME;
        EXECUTE PROCEDURE PROCEDURE_NAME;
    END
END /*CALLING_PACKAGE*/;
---------------------------------------
CREATE PACKAGE CALLING_PACKAGE
SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
END /*CALLING_PACKAGE*/;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    AS
    BEGIN
        EXECUTE PROCEDURE PROCEDURE_NAME;
        EXECUTE PROCEDURE PROCEDURE_NAME;
    END
END /*CALLING_PACKAGE*/;