CREATE EXCEPTION CUSTOM_EXCEPTION 'error';

CREATE PACKAGE PackF_Null_In_Exception
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Null_In_Exception 
   RETURNS VARCHAR(32765);
END;

CREATE PACKAGE BODY PackF_Null_In_Exception
AS BEGIN
   FUNCTION PF_Null_In_Exception
   RETURNS VARCHAR(32765)
   AS
   BEGIN
     EXCEPTION CUSTOM_EXCEPTION( 'Неправильный номер');
     /*EXCEPTION*/
     WHEN ANY DO BEGIN
     END
     RETURN '';
   END
END;