CREATE EXCEPTION CUSTOM_EXCEPTION 'error';

CREATE PROCEDURE P_Null_In_Exception
SQL SECURITY DEFINER
AS
BEGIN
  EXCEPTION CUSTOM_EXCEPTION( 'Неправильный номер');
  /*EXCEPTION*/
  WHEN ANY DO BEGIN
  END
END;