SELECT ASCII_VAL(NULL) FROM RDB$DATABASE;

SELECT ASCII_VAL('') FROM RDB$DATABASE;

SELECT ASCII_VAL('B') FROM RDB$DATABASE;

SELECT ASCII_VAL('CAT') FROM RDB$DATABASE;

SELECT ASCII_VAL('cat') FROM RDB$DATABASE;

SELECT ASCII_VAL('dog') FROM RDB$DATABASE;

SELECT ASCII_VAL(':') FROM RDB$DATABASE;