SELECT SUBSTR('ABCDEFGHIJK',3) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',3,4) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',3,0) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',-5) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',-5,4) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',-5,0) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',0) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',0,4) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',3,100) FROM DUAL;

SELECT SUBSTR('',3) FROM DUAL;

SELECT SUBSTR('ABCDEFGHIJK',-50) FROM DUAL;

SELECT SUBSTRB('ABCDEFG',5,4) FROM DUAL;

SELECT SUBSTRC('ABCDEFG',5,4) FROM DUAL;

SELECT SUBSTR2('ABCDEFG',5,4) FROM DUAL;

SELECT SUBSTR4('ABCDEFG',5,4) FROM DUAL;
