CREATE TRIGGER T_Grade_meaning1
    AFTER INSERT
    ON EMPLOYEES
    FOR EACH ROW
DECLARE
    CURSOR CURSOR_NAME RETURN EMPLOYEES%ROWTYPE;
    CURSOR CURSOR_NAME IS
        SELECT FIRST_NAME FROM EMPLOYEES;
BEGIN
    NULL;
END;