-- инициализация внутри PACKAGE и объявление внутри PACKAGE BODY
CREATE PACKAGE BOOK_INFO
IS
    CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE;
END;

CREATE PACKAGE BODY BOOK_INFO
IS
    CURSOR BOOKS_CUR
        RETURN BOOKS%ROWTYPE
    IS
    SELECT *
    FROM BOOKS;
END;


-- инициализация и объявление внутри PACKAGE BODY
CREATE PACKAGE BOOK_INFO
IS

END;

CREATE OR REPLACE PACKAGE BODY BOOK_INFO
IS
    CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE;
    CURSOR BOOKS_CUR
        RETURN BOOKS%ROWTYPE
        IS
    SELECT *
    FROM BOOKS;
END;

-- инициализация и объявление внутри PACKAGE
CREATE OR REPLACE PACKAGE BOOK_INFO
IS
    CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE;
    CURSOR BOOKS_CUR
        RETURN BOOKS%ROWTYPE
            IS
    SELECT *
    FROM BOOKS;
END;

CREATE PACKAGE BODY BOOK_INFO
IS

END;


-- объявление и инициализация в функции внутри пакета

CREATE OR REPLACE PACKAGE BOOK_INFO
IS
    FUNCTION TEST_F RETURN BOOLEAN;
END;

CREATE OR REPLACE PACKAGE BODY BOOK_INFO
IS
    FUNCTION TEST_F
        RETURN BOOLEAN
    IS
        CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE;
        CURSOR BOOKS_CUR
            RETURN BOOKS%ROWTYPE
            IS
            SELECT *
            FROM BOOKS;
    BEGIN

    RETURN TRUE;
    END;
END;
