-- инициализация внутри PACKAGE и объявление внутри PACKAGE BODY
/*CANNOT DECLARE CURSOR INSIDE PACKAGE DECLARATION*/
CREATE PACKAGE BOOK_INFO
AS BEGIN
    /*[-unconvertible CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE];*/
END;

/*CANNOT CREATE CURSOR IN PACKAGE BODY*/
CREATE PACKAGE BODY BOOK_INFO
AS BEGIN
    /*[-unconvertible CURSOR BOOKS_CUR
    RETURN BOOKS%ROWTYPE
    IS
        SELECT *
        FROM BOOKS];*/
END;

-- инициализация и объявление внутри PACKAGE BODY
CREATE PACKAGE BOOK_INFO
AS BEGIN

END;

/*CANNOT CREATE CURSOR IN PACKAGE BODY*/
CREATE PACKAGE BODY BOOK_INFO
AS BEGIN
    /*[-unconvertible CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE];*/
    /*[-unconvertible CURSOR BOOKS_CUR
    RETURN BOOKS%ROWTYPE
    IS
        SELECT *
        FROM BOOKS];*/
END;

-- инициализация и объявление внутри PACKAGE
/*CANNOT DECLARE CURSOR INSIDE PACKAGE DECLARATION*/
CREATE PACKAGE BOOK_INFO
AS BEGIN
    /*[-unconvertible CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE];*/
    /*[-unconvertible CURSOR BOOKS_CUR
    RETURN BOOKS%ROWTYPE
    IS
        SELECT *
        FROM BOOKS];*/
END;

CREATE PACKAGE BODY BOOK_INFO
AS BEGIN

END;

-- объявление и инициализация в функции внутри пакета
CREATE OR ALTER PACKAGE BOOK_INFO
AS BEGIN
    FUNCTION TEST_F RETURNS BOOLEAN;
END;

RECREATE   PACKAGE BODY BOOK_INFO
AS BEGIN
    FUNCTION TEST_F
    RETURNS BOOLEAN
    AS
        /*[-unconvertible DECLARE BOOKS_CUR RETURN TYPE OF TABLE BOOKS];*/
        DECLARE BOOKS_CUR CURSOR FOR
            (SELECT *FROM BOOKS);
    BEGIN

    RETURN TRUE;
    END
END;