CREATE OR ALTER PROCEDURE LOC_VAR
    AS
    DECLARE var_ NUMERIC(34, 8) = 5;
BEGIN
    IF (TRUE) THEN
        var_ = :var_ /0 ;
/*EXCEPTION*/
    WHEN GDSCODE EXCEPTION_INTEGER_DIVIDE_BY_ZERO, GDSCODE EXCEPTION_FLOAT_DIVIDE_BY_ZERO DO
        BEGIN

        END
END;