CREATE EXCEPTION USER_EXCEPTION 'USER_EXCEPTION';
CREATE OR ALTER PROCEDURE LOC_VAR AS
/*USER_EXCEPTION EXCEPTION;*/
BEGIN
    IF (TRUE) THEN
        EXCEPTION NO_DATA_FOUND;
/*EXCEPTION*/
    WHEN EXCEPTION USER_EXCEPTION, GDSCODE CURSOR_ALREADY_OPEN DO
        BEGIN

        END
END;