CREATE EXCEPTION USER_EXCEPTION 'USER_EXCEPTION';

CREATE OR ALTER PROCEDURE LOC_VAR AS
    /*USER_EXCEPTION EXCEPTION;*/
BEGIN
    IF (TRUE) THEN
        EXCEPTION USER_EXCEPTION;
/*EXCEPTION*/
    WHEN EXCEPTION USER_EXCEPTION DO
        BEGIN

        END
END;