package ru.redsoft.ora2rdb;

public enum BlockType {
    UNKNOWN,
    FUNCTION_AND_PROCEDURE_AND_TRIGGER,
    SIMPLE_COMMAND,
    SIMPLE_COMMAND_INSIDE_PACKAGE,
    PACKAGE,
    TYPE_BODY,
    ANONYMOUS_BLOCK,
}
