CREATE TRIGGER T_Sqlfound
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
  tmp BOOLEAN;
BEGIN
  tmp := SQL%FOUND;
  UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
  tmp := SQL%FOUND;
END;