CREATE PACKAGE PackF_Sqlfound
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Sqlfound 
   RETURNS VARCHAR(32765);
END;

CREATE PACKAGE BODY PackF_Sqlfound
AS BEGIN
   FUNCTION PF_Sqlfound
   RETURNS VARCHAR(32765)
   AS
     DECLARE tmp BOOLEAN;
   BEGIN
     tmp = DECODE(ROW_COUNT, 0, FALSE, TRUE);
     UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
     tmp = DECODE(ROW_COUNT, 0, FALSE, TRUE);
     RETURN '';
   END
END;