CREATE PACKAGE PackF_Sqlfound
AS
   FUNCTION PF_Sqlfound 
   RETURN VARCHAR2;
END;

CREATE PACKAGE BODY PackF_Sqlfound
AS
   FUNCTION PF_Sqlfound
   RETURN VARCHAR2
   IS
     tmp BOOLEAN;
   BEGIN
     tmp := SQL%FOUND;
     UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
     tmp := SQL%FOUND;
     RETURN '';
   END;
END;