CREATE FUNCTION F_Sqlfound
RETURNS VARCHAR(32765)
SQL SECURITY DEFINER
AS
  DECLARE tmp BOOLEAN;
BEGIN
  tmp = DECODE(ROW_COUNT, 0, FALSE, TRUE);
  UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
  tmp = DECODE(ROW_COUNT, 0, FALSE, TRUE);
  RETURN '';
END;