CREATE PACKAGE PackP_Sqlfound
SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PP_Sqlfound;
END;

CREATE PACKAGE BODY PackP_Sqlfound
AS
BEGIN
    PROCEDURE PP_Sqlfound
    AS
      DECLARE tmp BOOLEAN;
    BEGIN
      tmp = DECODE(ROW_COUNT, 0, FALSE, TRUE);
      UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
      tmp = DECODE(ROW_COUNT, 0, FALSE, TRUE);
    END
END;