INSERT INTO COUNTRY
(COUNTRY, CURRENCY)
VALUES
    ( 'RUSSIA', 'RUBLE')
    RETURNING COUNTRY, CURRENCY INTO :BIND2 , :BIND1;
-- допускается использовать ключевое слово RETURN
INSERT INTO COUNTRY
(COUNTRY, CURRENCY)
VALUES
    ( 'RUSSIA', 'RUBLE')
    RETURN COUNTRY, CURRENCY INTO :BIND2 , :BIND1;