CREATE PACKAGE PackF_Sqlnotfound
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Sqlnotfound 
   RETURNS VARCHAR(32765);
END;

CREATE PACKAGE BODY PackF_Sqlnotfound
AS BEGIN
   FUNCTION PF_Sqlnotfound
   RETURNS VARCHAR(32765)
   AS
     DECLARE tmp BOOLEAN;
   BEGIN
     tmp = DECODE(ROW_COUNT, 0, TRUE, FALSE);
     UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
     tmp = DECODE(ROW_COUNT, 0, TRUE, FALSE);
     RETURN '';
   END
END;