CREATE FUNCTION F_Sqlnotfound
RETURN VARCHAR2
IS
  tmp BOOLEAN;
BEGIN
  tmp := SQL%NOTFOUND;
  UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
  tmp := SQL%NOTFOUND;
  RETURN '';
END;