CREATE TRIGGER T_Sqlnotfound
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
  tmp BOOLEAN;
BEGIN
  tmp := SQL%NOTFOUND;
  UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
  tmp := SQL%NOTFOUND;
END;