CREATE GLOBAL TEMPORARY TABLE TEAM (
    VAL VARCHAR(15)
);

EXECUTE BLOCK
    AS
    /*TYPE FOURSOME IS VARRAY(4) OF VARCHAR(15);*/

    /*TEAM FOURSOME;*/
    DECLARE NUMELEMENTS INTEGER;
    DECLARE ELEMENTEXISTS BOOLEAN;
    DECLARE FIRSTELEMENT VARCHAR(100);
    DECLARE LASTELEMENT VARCHAR(100);
    DECLARE LIMITVAR VARCHAR(100);
BEGIN
    /*TEAM := FOURSOME('JOHN', 'MARY', 'ALBERTO', 'JUANITA');*/
    INSERT INTO TEAM VALUES('JOHN');
    INSERT INTO TEAM VALUES('MARY');
    INSERT INTO TEAM VALUES('ALBERTO');
    INSERT INTO TEAM VALUES('JUANITA');

    NUMELEMENTS = (SELECT COUNT(*) FROM TEAM);
    -- EXTEND

    -- GET ELEMENT BY ID (2)
    FIRSTELEMENT = (SELECT FIRST 1 SKIP 1 VAL FROM TEAM);
   -- ACCESS THE FIRST ELEMENT OF THE VARRAY DIRECTLY USING INDEX 1
    FIRSTELEMENT = (SELECT FIRST 1 VAL FROM TEAM);
    -- ACCESS THE LAST ELEMENT OF THE VARRAY USING THE COUNT METHOD TO DETERMINE THE NUMBER OF ELEMENTS
    LASTELEMENT = (SELECT SKIP ((SELECT COUNT(*) - 1 FROM TEAM)) VAL FROM TEAM);
    -- DELETE (DELETE ALL ELEMENTS FROM VARRAY)
    DELETE FROM TEAM;
    -- DELETE LAST ELEMENT OF VARRAY
    DELETE FROM TEAM ROWS (SELECT COUNT(*) FROM TEAM) TO (SELECT COUNT(*) FROM TEAM);
    -- TRIM(N) - DELETE LAST N ELEMENTS OF VARRAY
    DELETE FROM TEAM ROWS (SELECT COUNT(*) - 1 FROM TEAM) TO (SELECT COUNT(*) FROM TEAM);
    -- ONLY VARRAY HAVE LIMIT
    LIMITVAR = (SELECT COUNT(*) FROM TEAM);
    -- EXISTS IS A FUNCTION THAT TELLS YOU WHETHER THE SPECIFIED ELEMENT OF A VARRAY OR NESTED TABLE EXISTS.
    ELEMENTEXISTS = (2 <= (SELECT COUNT(*) FROM TEAM)); -- проверяет, что второй элемент существует
END;