CREATE TRIGGER T_Exit
BEFORE INSERT ON EMPLOYEES
SQL SECURITY DEFINER
AS
  DECLARE i_FOR1 INTEGER;
  DECLARE bound_i_FOR1 INTEGER;
BEGIN
  i_FOR1 = 1;
  bound_i_FOR1 = 3;
  WHILE (i_FOR1 <= bound_i_FOR1) DO
  BEGIN 
    if (i_FOR1 = 3) then 
      LEAVE;
    i_FOR1 = i_FOR1 + 1;
  END
  i_FOR1 = bound_i_FOR1;
END;