CREATE GLOBAL TEMPORARY TABLE VEC_F_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_From_Nested_table
RETURNS VARCHAR(100)
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('John');
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('Mary');
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('Alberto');
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_F_From_Nested_table
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + i_FOR1; 
   END
END;