INSERT ALL
      INTO SALES (PROD_ID, CUST_ID, TIME_ID, AMOUNT)
      VALUES (PRODUCT_ID, CUSTOMER_ID, WEEKLY_START_DATE, SALES_SUN)
      INTO SALES (PROD_ID, CUST_ID, TIME_ID, AMOUNT)
      VALUES (PRODUCT_ID, CUSTOMER_ID, WEEKLY_START_DATE+1, SALES_MON)
SELECT PRODUCT_ID, CUSTOMER_ID, WEEKLY_START_DATE, SALES_SUN,
       SALES_MON, SALES_TUE, SALES_WED, SALES_THU, SALES_FRI, SALES_SAT
FROM SALES_INPUT_TABLE;
