-- порядок вставки значений изменился
INSERT INTO SALES (PROD_ID, CUST_ID, TIME_ID, AMOUNT)
    SELECT PRODUCT_ID, CUSTOMER_ID, WEEKLY_START_DATE, SALES_SUN
    FROM SALES_INPUT_TABLE;
INSERT INTO SALES (PROD_ID, CUST_ID, TIME_ID, AMOUNT)
    SELECT PRODUCT_ID, CUSTOMER_ID, WEEKLY_START_DATE+1, SALES_MON
    FROM SALES_INPUT_TABLE;