CREATE OR ALTER FUNCTION FUNCTION_NAME
    RETURNS BOOLEAN
    SQL SECURITY DEFINER
AS
    DECLARE I NUMERIC(34, 8);
BEGIN
    I = 0;
    WHILE (TRUE) DO BEGIN
        I = :I + 1;
        IF( (:I > 5) ) THEN LEAVE;
    END
RETURN TRUE;
END /*FUNCTION_NAME*/;