CREATE FUNCTION DIV (m NUMERIC(34,10), n NUMERIC(34,10))
RETURNS NUMERIC(34,10)
AS
BEGIN
  RETURN cast(m as NUMERIC(34,10))/cast(n as NUMERIC(34,10));
END;

CREATE FUNCTION MOD_clon (m NUMERIC(34,10), n NUMERIC(34,10))
RETURNS NUMERIC(34,10)
AS
BEGIN
  IF (n = 0) THEN RETURN m;
  IF (m*n >= 0) THEN
    RETURN m - n*FLOOR(div(m,n));
  ELSE 
    RETURN m - n*CEIL(div(m,n));
END;

SELECT MOD_clon(7.5, 2.1) FROM RDB$DATABASE;
SELECT MOD_clon(-7.5, -2.1) FROM RDB$DATABASE;
SELECT MOD_clon(-7.5, 2.1) FROM RDB$DATABASE;
SELECT MOD_clon(7.5, -2.1) FROM RDB$DATABASE;

SELECT MOD_clon(11, 4) FROM RDB$DATABASE;
SELECT MOD_clon(-11, -4) FROM RDB$DATABASE;
SELECT MOD_clon(-11, 4) FROM RDB$DATABASE;
SELECT MOD_clon(11, -4) FROM RDB$DATABASE;

SELECT MOD_clon(10, 4) FROM RDB$DATABASE;
SELECT MOD_clon(-10, -4) FROM RDB$DATABASE;
SELECT MOD_clon(-10, 4) FROM RDB$DATABASE;
SELECT MOD_clon(10, -4) FROM RDB$DATABASE;
