CREATE FUNCTION NANVL (m DECFLOAT(16), n DECFLOAT(16))
RETURNS DECFLOAT(16)
AS
BEGIN
  RETURN IIF (COMPARE_DECFLOAT(m, m) = 3, n, m);
END;

SELECT NANVL (cast ('nan' as DECFLOAT(16)), 0) FROM RDB$DATABASE;
SELECT NANVL (cast (123.45 as DECFLOAT(16)), 0) FROM RDB$DATABASE;