SELECT REMAINDER(7.5, 2.1) FROM DUAL;
SELECT REMAINDER(-7.5, -2.1) FROM DUAL;
SELECT REMAINDER(-7.5, 2.1) FROM DUAL;
SELECT REMAINDER(7.5, -2.1) FROM DUAL;

SELECT REMAINDER(11, 4) FROM DUAL;
SELECT REMAINDER(-11, -4) FROM DUAL;
SELECT REMAINDER(-11, 4) FROM DUAL;
SELECT REMAINDER(11, -4) FROM DUAL;

SELECT REMAINDER(10, 4) FROM DUAL;
SELECT REMAINDER(-10, -4) FROM DUAL;
SELECT REMAINDER(-10, 4) FROM DUAL;
SELECT REMAINDER(10, -4) FROM DUAL;

SELECT REMAINDER(7, 2) FROM DUAL;
SELECT REMAINDER(-7, -2) FROM DUAL;
SELECT REMAINDER(-7, 2) FROM DUAL;
SELECT REMAINDER(7, -2) FROM DUAL;
