CREATE FUNCTION round_clon (m NUMERIC(34,10))
RETURNS INTEGER
AS
BEGIN
  RETURN CASE 
           WHEN MOD(m, 2) != 0 AND (m-0.5)=FLOOR(m-0.5) THEN IIF (m >= 0, FLOOR(m), CEIL(m))     
           WHEN MOD(m, 2) = 0  AND (m-0.5)=FLOOR(m-0.5) THEN IIF (m >= 0, CEIL(m), FLOOR(m))   
         ELSE ROUND(m) end;
END;

CREATE FUNCTION DIV (m NUMERIC(34,10), n NUMERIC(34,10))
RETURNS NUMERIC(34,10)
AS
BEGIN
  RETURN cast(m as NUMERIC(34,10))/cast(n as NUMERIC(34,10));
END;

CREATE FUNCTION REMAINDER (m NUMERIC(34,10), n NUMERIC(34,10))
RETURNS NUMERIC(34,10)
AS
BEGIN
  RETURN m - n*round_clon(div(m,n));
END;


SELECT REMAINDER(7.5, 2.1) FROM RDB$DATABASE;
SELECT REMAINDER(-7.5, -2.1) FROM RDB$DATABASE;
SELECT REMAINDER(-7.5, 2.1) FROM RDB$DATABASE;
SELECT REMAINDER(7.5, -2.1) FROM RDB$DATABASE;

SELECT REMAINDER(11, 4) FROM RDB$DATABASE;
SELECT REMAINDER(-11, -4) FROM RDB$DATABASE;
SELECT REMAINDER(-11, 4) FROM RDB$DATABASE;
SELECT REMAINDER(11, -4) FROM RDB$DATABASE;

SELECT REMAINDER(10, 4) FROM RDB$DATABASE;
SELECT REMAINDER(-10, -4) FROM RDB$DATABASE;
SELECT REMAINDER(-10, 4) FROM RDB$DATABASE;
SELECT REMAINDER(10, -4) FROM RDB$DATABASE;

SELECT REMAINDER(7, 2) FROM RDB$DATABASE;
SELECT REMAINDER(-7, -2) FROM RDB$DATABASE;
SELECT REMAINDER(-7, 2) FROM RDB$DATABASE;
SELECT REMAINDER(7, -2) FROM RDB$DATABASE;
