CREATE PROCEDURE GET_BAL(ACC_NO VARCHAR(32765))
RETURNS ( RET_VAL BOOLEAN,
ACC_NO_OUT VARCHAR(32765))
    SQL SECURITY DEFINER
    AS
BEGIN

    RET_VAL = TRUE;
    ACC_NO_OUT = ACC_NO;
    SUSPEND;
    EXIT;
END;