/* Процедура */
CREATE GLOBAL TEMPORARY TABLE VEC_P_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_From_Nested_table
AS
  /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_P_From_Nested_table(VAL) VALUES ('John');
   INSERT INTO VEC_P_From_Nested_table(VAL) VALUES ('Mary');
   INSERT INTO VEC_P_From_Nested_table(VAL) VALUES ('Alberto');
   INSERT INTO VEC_P_From_Nested_table(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_P_From_Nested_table
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + i_FOR1; 
   END
END;

/* Функция */
CREATE GLOBAL TEMPORARY TABLE VEC_F_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_From_Nested_table
RETURNS VARCHAR(100)
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('John');
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('Mary');
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('Alberto');
   INSERT INTO VEC_F_From_Nested_table(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_F_From_Nested_table
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + i_FOR1; 
   END
END;

/* Пакет */
CREATE GLOBAL TEMPORARY TABLE VEC_Pack_From_Nested_table_PF_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_From_Nested_table_PP_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_From_Nested_table
AS BEGIN
   FUNCTION PF_From_Nested_table
   RETURNS VARCHAR(100);
   PROCEDURE PP_From_Nested_table; 
END; 

/* Тело пакета */
RECREATE PACKAGE BODY Pack_From_Nested_table
AS BEGIN
   FUNCTION PF_From_Nested_table
   RETURNS VARCHAR(100)
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
   BEGIN
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC_Pack_From_Nested_table_PF_From_Nested_table
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     RETURN summa;
   END

   PROCEDURE PP_From_Nested_table
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
   BEGIN
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC_Pack_From_Nested_table_PP_From_Nested_table
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
   END  
END;  

/* Триггер DML */
CREATE GLOBAL TEMPORARY TABLE VEC_T_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER TRIGGER T_From_Nested_table
  AFTER INSERT 
  ON students
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_T_From_Nested_table(VAL) VALUES ('John');
   INSERT INTO VEC_T_From_Nested_table(VAL) VALUES ('Mary');
   INSERT INTO VEC_T_From_Nested_table(VAL) VALUES ('Alberto');
   INSERT INTO VEC_T_From_Nested_table(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_T_From_Nested_table
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + i_FOR1; 
   END
END;

/* Анонимный блок */
CREATE GLOBAL TEMPORARY TABLE VEC_NestTable_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

EXECUTE BLOCK 
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('John');
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('Mary');
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('Alberto');
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_NestTable_1
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + i_FOR1; 
   END
END;

