/* Процедура */
CREATE GLOBAL TEMPORARY TABLE VEC_P_From_Varray (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_From_Varray
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('John');
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('Mary');
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('Alberto');
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_P_From_Varray
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + :i_FOR1; 
   END
END;

/* Функция */
CREATE GLOBAL TEMPORARY TABLE VEC_F_From_Varray (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_From_Varray
RETURNS VARCHAR(100)
AS
   /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_F_From_Varray(VAL) VALUES ('John');
   INSERT INTO VEC_F_From_Varray(VAL) VALUES ('Mary');
   INSERT INTO VEC_F_From_Varray(VAL) VALUES ('Alberto');
   INSERT INTO VEC_F_From_Varray(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_F_From_Varray
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + :i_FOR1; 
   END
END;

/* Пакет */
CREATE GLOBAL TEMPORARY TABLE VEC_Pack_From_Varray_PF_From_Varray (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_From_Varray_PP_From_Varray (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_From_Varray
AS BEGIN
   FUNCTION PF_From_Varray
   RETURNS VARCHAR(100);
   PROCEDURE PP_From_Varray; 
END; 

/* Тело пакета */
RECREATE PACKAGE BODY Pack_From_Varray
AS BEGIN
   FUNCTION PF_From_Varray
   RETURNS VARCHAR(100)
   AS
     /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
     /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
   BEGIN
     INSERT INTO VEC_Pack_From_Varray_PF_From_Varray(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_From_Varray_PF_From_Varray(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_From_Varray_PF_From_Varray(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_From_Varray_PF_From_Varray(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC_Pack_From_Varray_PF_From_Varray
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + :i_FOR1; 
     END
     RETURN summa;
   END

   PROCEDURE PP_From_Varray
   AS
     /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
     /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
   BEGIN
     INSERT INTO VEC_Pack_From_Varray_PP_From_Varray(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_From_Varray_PP_From_Varray(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_From_Varray_PP_From_Varray(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_From_Varray_PP_From_Varray(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC_Pack_From_Varray_PP_From_Varray
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + :i_FOR1; 
     END
   END  
END;  

/* Триггер DML */
CREATE GLOBAL TEMPORARY TABLE VEC_T_From_Varray (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER TRIGGER T_From_Varray
  AFTER INSERT 
  ON students
AS
   /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_T_From_Varray(VAL) VALUES ('John');
   INSERT INTO VEC_T_From_Varray(VAL) VALUES ('Mary');
   INSERT INTO VEC_T_From_Varray(VAL) VALUES ('Alberto');
   INSERT INTO VEC_T_From_Varray(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_T_From_Varray
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + :i_FOR1; 
   END
END;

/* Анонимный блок */
CREATE GLOBAL TEMPORARY TABLE VEC_Varray_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

EXECUTE BLOCK 
AS
   /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_Varray_1(VAL) VALUES ('John');
   INSERT INTO VEC_Varray_1(VAL) VALUES ('Mary');
   INSERT INTO VEC_Varray_1(VAL) VALUES ('Alberto');
   INSERT INTO VEC_Varray_1(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_Varray_1
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + :i_FOR1; 
   END
END;
