/* Процедура */
CREATE GLOBAL TEMPORARY TABLE VEC1_P_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_P_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_multiple
AS
  /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
  /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
  /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
  /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa INTEGER = 0;
  DECLARE i_FOR1 INTEGER;
BEGIN
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Olivia');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('William');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Emma');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Henry');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Grace');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('John');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('Mary');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('Alberto');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('Juanita');
  FOR SELECT ID FROM VEC1_P_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  FOR SELECT ID FROM VEC2_P_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  WHILE (1=1) DO
  BEGIN
    i_FOR1 = 100;
    summa = :summa + i_FOR1; 
    LEAVE;
  END
END; 

/* Функция */
CREATE GLOBAL TEMPORARY TABLE VEC1_F_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_F_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_multiple
RETURNS VARCHAR(150)
AS
  /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
  /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
  /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
  /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa INTEGER = 0;
  DECLARE i_FOR1 INTEGER;
BEGIN
  INSERT INTO VEC1_F_multiple(VAL) VALUES ('Olivia');
  INSERT INTO VEC1_F_multiple(VAL) VALUES ('William');
  INSERT INTO VEC1_F_multiple(VAL) VALUES ('Emma');
  INSERT INTO VEC1_F_multiple(VAL) VALUES ('Henry');
  INSERT INTO VEC1_F_multiple(VAL) VALUES ('Grace');
  INSERT INTO VEC2_F_multiple(VAL) VALUES ('John');
  INSERT INTO VEC2_F_multiple(VAL) VALUES ('Mary');
  INSERT INTO VEC2_F_multiple(VAL) VALUES ('Alberto');
  INSERT INTO VEC2_F_multiple(VAL) VALUES ('Juanita');
  FOR SELECT ID FROM VEC1_F_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  FOR SELECT ID FROM VEC2_F_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  WHILE (1=1) DO
  BEGIN
    i_FOR1 = 100;
    summa = :summa + i_FOR1; 
    LEAVE;
  END
  RETURN 0;
END; 

/* Пакет */
CREATE GLOBAL TEMPORARY TABLE VEC1_Pack_multiple_PF_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_Pack_multiple_PF_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC1_Pack_multiple_PP_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_Pack_multiple_PP_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_multiple
AS BEGIN
   FUNCTION PF_multiple
   RETURNS VARCHAR(150);
   PROCEDURE PP_multiple; 
END; 

/* Тело пакета */
RECREATE PACKAGE BODY Pack_multiple
AS BEGIN
   FUNCTION PF_multiple
   RETURNS VARCHAR(150)
   AS
     /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
     /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
     /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
     /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
  BEGIN
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Olivia');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('William');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Emma');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Henry');
     INSERT INTO VEC1_Pack_multiple_PF_multiple(VAL) VALUES ('Grace');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('John');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('Mary');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('Alberto');
     INSERT INTO VEC2_Pack_multiple_PF_multiple(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC1_Pack_multiple_PF_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     FOR SELECT ID FROM VEC2_Pack_multiple_PF_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     WHILE (1=1) DO
     BEGIN
       i_FOR1 = 100;
       summa = :summa + i_FOR1; 
       LEAVE;
     END
      RETURN 0;
    END

   PROCEDURE PP_multiple
   AS
     /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
     /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
     /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
     /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
  BEGIN
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Olivia');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('William');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Emma');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Henry');
     INSERT INTO VEC1_Pack_multiple_PP_multiple(VAL) VALUES ('Grace');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('John');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('Mary');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('Alberto');
     INSERT INTO VEC2_Pack_multiple_PP_multiple(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC1_Pack_multiple_PP_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     FOR SELECT ID FROM VEC2_Pack_multiple_PP_multiple
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     WHILE (1=1) DO
     BEGIN
       i_FOR1 = 100;
       summa = :summa + i_FOR1; 
       LEAVE;
     END
   END
END; 

/* Триггер DML */
CREATE GLOBAL TEMPORARY TABLE VEC1_T_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_T_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER TRIGGER T_multiple
  AFTER INSERT 
  ON students
AS
  /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
  /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
  /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
  /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa INTEGER = 0;
  DECLARE i_FOR1 INTEGER;
BEGIN
  INSERT INTO VEC1_T_multiple(VAL) VALUES ('Olivia');
  INSERT INTO VEC1_T_multiple(VAL) VALUES ('William');
  INSERT INTO VEC1_T_multiple(VAL) VALUES ('Emma');
  INSERT INTO VEC1_T_multiple(VAL) VALUES ('Henry');
  INSERT INTO VEC1_T_multiple(VAL) VALUES ('Grace');
  INSERT INTO VEC2_T_multiple(VAL) VALUES ('John');
  INSERT INTO VEC2_T_multiple(VAL) VALUES ('Mary');
  INSERT INTO VEC2_T_multiple(VAL) VALUES ('Alberto');
  INSERT INTO VEC2_T_multiple(VAL) VALUES ('Juanita');
  FOR SELECT ID FROM VEC1_T_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  FOR SELECT ID FROM VEC2_T_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  WHILE (1=1) DO
  BEGIN
    i_FOR1 = 100;
    summa = :summa + i_FOR1; 
    LEAVE;
  END
END;

/* Анонимный блок */
CREATE GLOBAL TEMPORARY TABLE VEC1_Varray_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_NestTable_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

EXECUTE BLOCK 
AS
  /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
  /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
  /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
  /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */ 
  DECLARE summa INTEGER = 0;
  DECLARE i_FOR1 INTEGER;
BEGIN
  INSERT INTO VEC1_Varray_1(VAL) VALUES ('Olivia');
  INSERT INTO VEC1_Varray_1(VAL) VALUES ('William');
  INSERT INTO VEC1_Varray_1(VAL) VALUES ('Emma');
  INSERT INTO VEC1_Varray_1(VAL) VALUES ('Henry');
  INSERT INTO VEC1_Varray_1(VAL) VALUES ('Grace');
  INSERT INTO VEC2_NestTable_1(VAL) VALUES ('John');
  INSERT INTO VEC2_NestTable_1(VAL) VALUES ('Mary');
  INSERT INTO VEC2_NestTable_1(VAL) VALUES ('Alberto');
  INSERT INTO VEC2_NestTable_1(VAL) VALUES ('Juanita');
  FOR SELECT ID FROM VEC1_Varray_1
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  FOR SELECT ID FROM VEC2_NestTable_1
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  WHILE (1=1) DO
  BEGIN
    i_FOR1 = 100;
    summa = :summa + i_FOR1; 
    LEAVE;
  END
END;