/*CANNOT DECLARE CURSOR INSIDE PACKAGE DECLARATION*/
CREATE PACKAGE BOOK_INFO
AS
       /*CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE;*/
END;

/*CANNOT CREATE CURSOR IN PACKAGE BODY*/
CREATE PACKAGE BODY BOOK_INFO
AS
    /*CURSOR BOOKS_CUR
        RETURN BOOKS%ROWTYPE
    IS
SELECT *
FROM BOOKS
WHERE TITLE LIKE TITLE_FILTER_IN;*/
END;
