CREATE PACKAGE BOOK_INFO
IS
       CURSOR BOOKS_CUR RETURN BOOKS%ROWTYPE;
END;

CREATE PACKAGE BODY BOOK_INFO
IS
    CURSOR BOOKS_CUR
        RETURN BOOKS%ROWTYPE
    IS
SELECT *
FROM BOOKS
WHERE TITLE LIKE TITLE_FILTER_IN;
END;