CREATE PROCEDURE PROCEDURE_NAME
    SQL SECURITY DEFINER
AS
    DECLARE PROCEDURE NESTED_PROCEDURE_NAME
        AS
    BEGIN

    END
BEGIN
    EXECUTE PROCEDURE NESTED_PROCEDURE_NAME; -- 1
    EXECUTE PROCEDURE NESTED_PROCEDURE_NAME; -- 2

    EXECUTE PROCEDURE NESTED_PROCEDURE_NAME; -- 3
    EXECUTE PROCEDURE NESTED_PROCEDURE_NAME; -- 4
END;