CREATE PROCEDURE PROCEDURE_NAME
    SQL SECURITY DEFINER
    AS
    DECLARE out_value  VARCHAR(20) = 'value';
	DECLARE PROCEDURE NESTED_PROCEDURE_NAME(in_param  VARCHAR(32765))
	AS
    BEGIN

    END

BEGIN
    EXECUTE PROCEDURE NESTED_PROCEDURE_NAME(:out_value); -- 1
    EXECUTE PROCEDURE NESTED_PROCEDURE_NAME(:out_value); -- 2
END;