CREATE PROCEDURE PROCEDURE_NAME
    IS
    PROCEDURE NESTED_PROCEDURE_NAME
    IS
    BEGIN
        NULL;
    END;
BEGIN
    NESTED_PROCEDURE_NAME; -- 1
    NESTED_PROCEDURE_NAME(); -- 2

    PROCEDURE_NAME.NESTED_PROCEDURE_NAME; -- 3
    PROCEDURE_NAME.NESTED_PROCEDURE_NAME(); -- 4
END;