CREATE PACKAGE CALLING_PACKAGE_NAME
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME RETURNS VARCHAR(32765);
   PROCEDURE PROCEDURE_NAME;
END /*CALLING_PACKAGE_NAME*/;


CREATE PACKAGE BODY CALLING_PACKAGE_NAME
AS BEGIN
   FUNCTION FUNCTION_NAME
   RETURNS VARCHAR(32765)
   AS
		DECLARE out_value VARCHAR(50);
	    DECLARE in_value VARCHAR(50);
    BEGIN
        SELECT OUT_VALUE_OUT FROM PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(:out_value) INTO :out_value;

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(:in_value); -- in param

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

    END

    PROCEDURE PROCEDURE_NAME
    AS
    	DECLARE out_value VARCHAR(50);
        DECLARE in_value VARCHAR(50);
    BEGIN
        SELECT OUT_VALUE_OUT FROM PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(:out_value) INTO :out_value;

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(:in_value); -- in param

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

        EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

    END

END /*CALLING_PACKAGE_NAME*/;