CREATE  TRIGGER TRIGGER_NAME
BEFORE INSERT ON EMPLOYEES
SQL SECURITY DEFINER
AS
    DECLARE out_value VARCHAR(50);
    DECLARE in_value VARCHAR(50);
BEGIN
    SELECT OUT_VALUE_OUT FROM PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(:out_value) INTO :out_value; -- out param

    EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(:in_value); -- in param

    EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

    EXECUTE PROCEDURE PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

END;