CREATE FUNCTION FUNCTION_NAME
RETURN VARCHAR2
    IS
    out_value VARCHAR2(50);
    in_value VARCHAR2(50);
BEGIN
    PACKAGE_NAME.PROCEDURE_NAME_WITH_OUT_PARAMETER(out_value); -- out param

    PACKAGE_NAME.PROCEDURE_NAME_WITH_IN_PARAMETER(in_value); -- in param

    PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER(); -- without param

    PACKAGE_NAME.PROCEDURE_NAME_WITHOUT_PARAMETER; -- without param

END;