


CREATE OR ALTER PACKAGE Pack_Grade_meaning1
AS BEGIN
   FUNCTION PF_Grade_meaning1 (degree INTEGER)
   RETURN BOOLEAN;
   PROCEDURE PP_Grade_meaning1;
END /*PACK_GRADE_MEANING1*/;



RECREATE   PACKAGE BODY Pack_Grade_meaning1
AS BEGIN
   FUNCTION PF_Grade_meaning1 (degree INTEGER)
   RETURNS BOOLEAN
   AS
     DECLARE C1 CURSOR FOR
(SELECT LAST_NAME FROM EMPLOYEES
WHERE MANAGER_ID > 120
ORDER BY LAST_NAME);
  DECLARE VARIABLE C1_ITEM TYPE OF COLUMN EMPLOYEES.LAST_NAME;

BEGIN
OPEN C1;
FETCH C1 INTO C1_ITEM;
WHILE ( ROW_COUNT != 0 ) DO
BEGIN

FETCH C1 INTO C1_ITEM;
END
CLOSE C1;

RETURN TRUE;
END

   PROCEDURE PP_Grade_meaning1
AS
        DECLARE C1 CURSOR FOR
(SELECT LAST_NAME FROM EMPLOYEES
WHERE MANAGER_ID > 120
ORDER BY LAST_NAME);

  DECLARE VARIABLE C1_ITEM TYPE OF COLUMN EMPLOYEES.LAST_NAME;
BEGIN
OPEN C1;
FETCH C1 INTO C1_ITEM;
WHILE ( ROW_COUNT != 0 ) DO
BEGIN

FETCH C1 INTO C1_ITEM;
END
CLOSE C1;

END
END /*PACK_GRADE_MEANING1*/;