CREATE TRIGGER T_Grade_meaning1
  AFTER INSERT
  ON EMPLOYEES
  FOR EACH ROW
DECLARE
    CURSOR C1 IS
        SELECT LAST_NAME FROM EMPLOYEES
        WHERE MANAGER_ID > 120
        ORDER BY LAST_NAME;
BEGIN
    FOR ITEM IN C1
          LOOP
            NULL;
    END LOOP;
END T_Grade_meaning1;
