EXECUTE BLOCK
    AS

    DECLARE C1 CURSOR FOR
    (SELECT LAST_NAME FROM EMPLOYEES
    WHERE MANAGER_ID > 120);

  DECLARE VARIABLE C1_ITEM TYPE OF COLUMN EMPLOYEES.LAST_NAME;
BEGIN

    OPEN C1;
    FETCH C1 INTO C1_ITEM;
    WHILE ( ROW_COUNT != 0 ) DO
        BEGIN

        FETCH C1 INTO C1_ITEM;
        END
    CLOSE C1;

END;