CREATE PROCEDURE P_Grade_meaning1
IS
  CURSOR C1 IS
    SELECT LAST_NAME FROM EMPLOYEES
    WHERE MANAGER_ID > 120
    ORDER BY LAST_NAME;
BEGIN
    FOR ITEM IN C1
      LOOP
        NULL;
    END LOOP;
END;