CREATE PACKAGE PKG AS
BEGIN
    DECLARE TYPE EMPLOYEE_RECORD (
        EMP_ID NUMERIC(34, 8),
    	EMP_NAME VARCHAR(50),
   	    EMP_SALARY NUMERIC(34, 8)
    );
END;

EXECUTE BLOCK
    AS
    DECLARE EMP PKG.EMPLOYEE_RECORD = ROW(1000, 'ALEX', 5000);
BEGIN

END;