-- RED DATABASE SUPPORT ONLY DDL STATEMENT
/*
CREATE OR REPLACE TRIGGER TRG_AFTER_CREATE_TABLE
AFTER GRANT ON SCHEMA
BEGIN
    DBMS_OUTPUT.PUT_LINE('СОЗДАНА НОВАЯ DDL В СХЕМЕ HR: ' || ORA_DICT_OBJ_NAME);
END;
*/