CREATE TRIGGER T_Grade_meaning1
    AFTER INSERT
    ON EMPLOYEES
    SQL SECURITY DEFINER
AS
    DECLARE cur CURSOR FOR
        (SELECT * FROM employees);
	DECLARE VARIABLE cur_rec TYPE OF TABLE cur;
BEGIN

END;