INSERT INTO SMALL_ORDERS(ORDER_ID, ORDER_TOTAL, SALES_REP_ID , CUSTOMER_ID)
    SELECT ORDER_ID, ORDER_TOTAL, SALES_REP_ID, CUSTOMER_ID
    FROM ORDERS WHERE ORDER_TOTAL <= 100000;

INSERT INTO MEDIUM_ORDERS(ORDER_ID, ORDER_TOTAL, SALES_REP_ID , CUSTOMER_ID)
SELECT ORDER_ID, ORDER_TOTAL, SALES_REP_ID, CUSTOMER_ID
FROM ORDERS WHERE ORDER_TOTAL > 100000 AND ORDER_TOTAL <= 200000 ;

INSERT INTO LARGE_ORDERS(ORDER_ID, ORDER_TOTAL, SALES_REP_ID , CUSTOMER_ID)
    SELECT ORDER_ID, ORDER_TOTAL, SALES_REP_ID, CUSTOMER_ID
    FROM ORDERS WHERE ORDER_TOTAL > 200000;