CREATE FUNCTION FUNCTION_NAME
    RETURNS BOOLEAN
    SQL SECURITY DEFINER
    AS
    /*CURSOR CURSOR_NAME RETURN EMPLOYEES%ROWTYPE;*/
    DECLARE CURSOR_NAME CURSOR FOR
        (SELECT FIRST_NAME FROM EMPLOYEES);
BEGIN

END;