CREATE GLOBAL TEMPORARY TABLE VEC1_Pack_Few_Fors_PF_Few_Fors (
    K INTEGER,
    VAL INTEGER,
    CONSTRAINT PK_VEC1_Pack_Few_Fors_PF_Few_Fors  PRIMARY KEY (K)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_Pack_Few_Fors_PF_Few_Fors (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC1_Pack_Few_Fors_PP_Few_Fors (
    K INTEGER,
    VAL INTEGER,
    CONSTRAINT PK_VEC1_Pack_Few_Fors_PP_Few_Fors PRIMARY KEY (K)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_Pack_Few_Fors_PP_Few_Fors (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);


CREATE OR ALTER PACKAGE Pack_Few_Fors
AS BEGIN
   FUNCTION PF_Few_Fors
   RETURNS INTEGER;
   PROCEDURE PP_Few_Fors; 
END; 

RECREATE PACKAGE BODY Pack_Few_Fors
AS BEGIN
   FUNCTION PF_Few_Fors
   RETURNS INTEGER
   AS
     /* TYPE intvec_t IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER; */
     /* vec1 intvec_t := intvec_t(3 => 10, 1 => 11, 100 => 34); */
     /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
     /* vec2 varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE i_FOR1 INTEGER;
     DECLARE i_FOR2 VARCHAR(15);
   BEGIN
     UPDATE OR INSERT INTO VEC1_Pack_Few_Fors_PF_Few_Fors VALUES (3, 10);
     UPDATE OR INSERT INTO VEC1_Pack_Few_Fors_PF_Few_Fors VALUES (1, 11);
     UPDATE OR INSERT INTO VEC1_Pack_Few_Fors_PF_Few_Fors VALUES (100, 34);
     INSERT INTO VEC2_Pack_Few_Fors_PF_Few_Fors(VAL) VALUES ('John');
     INSERT INTO VEC2_Pack_Few_Fors_PF_Few_Fors(VAL) VALUES ('Mary');
     INSERT INTO VEC2_Pack_Few_Fors_PF_Few_Fors(VAL) VALUES ('Alberto');
     INSERT INTO VEC2_Pack_Few_Fors_PF_Few_Fors(VAL) VALUES ('Juanita');
     FOR SELECT VAL FROM VEC1_Pack_Few_Fors_PF_Few_Fors
     ORDER BY K ASC
     INTO :i_FOR1
     DO
     BEGIN
     END
     FOR SELECT VAL FROM VEC2_Pack_Few_Fors_PF_Few_Fors
     ORDER BY ID ASC
     INTO :i_FOR2
     DO
     BEGIN
     END
     RETURN 0;
   END

   PROCEDURE PP_Few_Fors
   AS
     /* TYPE intvec_t IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER; */
     /* vec1 intvec_t := intvec_t(3 => 10, 1 => 11, 100 => 34); */
     /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
     /* vec2 varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE i_FOR1 INTEGER;
     DECLARE i_FOR2 VARCHAR(15);
   BEGIN
     UPDATE OR INSERT INTO VEC1_Pack_Few_Fors_PP_Few_Fors VALUES (3, 10);
     UPDATE OR INSERT INTO VEC1_Pack_Few_Fors_PP_Few_Fors VALUES (1, 11);
     UPDATE OR INSERT INTO VEC1_Pack_Few_Fors_PP_Few_Fors VALUES (100, 34);
     INSERT INTO VEC2_Pack_Few_Fors_PP_Few_Fors(VAL) VALUES ('John');
     INSERT INTO VEC2_Pack_Few_Fors_PP_Few_Fors(VAL) VALUES ('Mary');
     INSERT INTO VEC2_Pack_Few_Fors_PP_Few_Fors(VAL) VALUES ('Alberto');
     INSERT INTO VEC2_Pack_Few_Fors_PP_Few_Fors(VAL) VALUES ('Juanita');
     FOR SELECT VAL FROM VEC1_Pack_Few_Fors_PP_Few_Fors
     ORDER BY K ASC
     INTO :i_FOR1
     DO
     BEGIN
     END
     FOR SELECT VAL FROM VEC2_Pack_Few_Fors_PP_Few_Fors
     ORDER BY ID ASC
     INTO :i_FOR2
     DO
     BEGIN
     END
   END
END; 