CREATE FUNCTION FUNCTION_NAME
RETURNS VARCHAR(32765)
SQL SECURITY DEFINER
AS
     DECLARE ret_val_n_f VARCHAR(20);

    DECLARE FUNCTION NESTED_FUNCTION_NAME
    RETURNS VARCHAR(32765)
    AS
    BEGIN
        RETURN 'nested_f';
    END
BEGIN
    ret_val_n_f = NESTED_FUNCTION_NAME();
    return 'value' || :ret_val_n_f;
END;