  CREATE TABLE "EMPLOYEES2"
   (
    "EMPLOYEE_ID" NUMERIC(34, 8) NOT NULL,
	"FIRST_NAME" VARCHAR(50) NOT NULL,
	"LAST_NAME" VARCHAR(50) NOT NULL,
	"JOB_TITLE" VARCHAR(100 ),
	"HIRE_DATE" DATE DEFAULT CURRENT_TIMESTAMP,
	"SALARY" NUMERIC(10, 2),
	 PRIMARY KEY ("EMPLOYEE_ID")
   );