CREATE TRIGGER T_Exit_Label_When
BEFORE INSERT ON EMPLOYEES
SQL SECURITY DEFINER
AS
  DECLARE x NUMERIC(34, 8) = 0;
BEGIN
  while1:
  WHILE (TRUE) DO 
  BEGIN
    x = :x + 1;
    IF (:x > 4) THEN
      LEAVE while1;
  END 
END;