CREATE OR REPLACE PACKAGE MY_TYPES AUTHID CURRENT_USER IS
    TYPE MY_AA IS TABLE OF VARCHAR2(20) INDEX BY PLS_INTEGER;
    FUNCTION INIT_MY_AA RETURN MY_AA;
END;

CREATE OR REPLACE PACKAGE BODY MY_TYPES IS
    FUNCTION INIT_MY_AA RETURN MY_AA IS
        RET MY_AA;
    BEGIN
        RETURN RET;
    END;
END;

