CREATE GLOBAL TEMPORARY TABLE RET (
    K NUMERIC(34, 8),
    VAL VARCHAR(64),
    CONSTRAINT PK_CITY_POPULATION PRIMARY KEY (K)
);

CREATE OR ALTER PACKAGE MY_TYPES SQL SECURITY INVOKER AS BEGIN
    /*TYPE MY_AA IS TABLE OF VARCHAR(20) INDEX BY INTEGER;*/
    PROCEDURE INIT_MY_AA;
END;

RECREATE PACKAGE BODY MY_TYPES AS BEGIN
    PROCEDURE INIT_MY_AA AS
         /*DECLARE RET MY_AA;*/
    BEGIN
        /*RETURN RET;*/
    END
END;