DECLARE

TYPE POPULATION IS TABLE OF NUMBER
    INDEX BY VARCHAR2(64);

    CITY_POPULATION  POPULATION;
    I  VARCHAR2(64);
    VAL NUMBER;

BEGIN
    VAL := CITY_POPULATION(I);

    I := CITY_POPULATION.LAST;
    I := CITY_POPULATION.FIRST;
    I := CITY_POPULATION.NEXT(I);
    I := CITY_POPULATION.COUNT();
    I := CITY_POPULATION.PRIOR('MIDLAND');
    bool_val := CITY_POPULATION.EXISTS('MIDLAND');
    CITY_POPULATION.DELETE('MIDLAND');
END;