CREATE GLOBAL TEMPORARY TABLE CITY_POPULATION (
    K VARCHAR(64),
    VAL NUMERIC(34, 8),
    CONSTRAINT PK_CITY_POPULATION PRIMARY KEY (K)
);

EXECUTE BLOCK
    AS

/*TYPE POPULATION IS TABLE OF NUMBER
    INDEX BY VARCHAR2(64);*/

    /*CITY_POPULATION  POPULATION;*/
    DECLARE I  VARCHAR(64);
    DECLARE VAL NUMERIC(34, 8);

BEGIN
    VAL = (SELECT VAL FROM CITY_POPULATION WHERE K = :I);  -- get value by id

    I = (SELECT FIRST 1 K FROM CITY_POPULATION ORDER BY K DESC); -- LAST
    I = (SELECT FIRST 1 K FROM CITY_POPULATION ORDER BY K ASC); -- FIRST
    I = (SELECT FIRST 1 K FROM CITY_POPULATION WHERE K > :I ORDER BY K ASC) -- NEXT
    I = (SELECT COUNT(*) FROM CITY_POPULATION); -- COUNT
    I = (SELECT FIRST 1 K FROM CITY_POPULATION WHERE K > 'MIDLAND' ORDER BY K DESC); -- PRIOR
    bool_var = (SELECT COUNT(*) > 0 FROM CITY_POPULATION WHERE K = 'MIDLAND'); -- EXISTS
    DELETE FROM CITY_POPULATION WHERE K = 'MIDLAND'; --DELETE
END;
