CREATE PACKAGE CALLING_PACKAGE
AS
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURN VARCHAR2;
END CALLING_PACKAGE;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURN VARCHAR2
   IS
        out_value VARCHAR2(50);
    BEGIN
        out_value := 'out_value';
        PROCEDURE_NAME(out_value);
    END;
END CALLING_PACKAGE;
-----------------------------------------------
CREATE PACKAGE CALLING_PACKAGE
AS
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
END CALLING_PACKAGE;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    IS
        out_value VARCHAR2(50);
    BEGIN
        out_value := 'out_value';
        PROCEDURE_NAME(out_value);
    END;
END CALLING_PACKAGE;