CREATE PACKAGE CALLING_PACKAGE
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURNS VARCHAR(32765);
END /*CALLING_PACKAGE*/;

CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURNS VARCHAR(32765)
    AS
        DECLARE out_value VARCHAR(50);
    BEGIN
        out_value = 'out_value';
        SELECT OUT_PARAMETER_OUT FROM PROCEDURE_NAME(:out_value) INTO :out_value;
    END
END /*CALLING_PACKAGE*/;
-----------------------------------------------
CREATE PACKAGE CALLING_PACKAGE
SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
END /*CALLING_PACKAGE*/;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    AS
        DECLARE out_value VARCHAR(50);
    BEGIN
        out_value = 'out_value';
        SELECT OUT_PARAMETER_OUT FROM PROCEDURE_NAME(:out_value) INTO :out_value;
    END
END /*CALLING_PACKAGE*/;