CREATE GLOBAL TEMPORARY TABLE VEC_F_Same_Name_Var (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_Same_Name_Var
RETURNS VARCHAR(100)
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
  /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa VARCHAR(100) = '';
  DECLARE i VARCHAR(15);
  DECLARE j VARCHAR(15);
  DECLARE i_FOR1 INTEGER;
  DECLARE j_FOR1 VARCHAR(15);
BEGIN
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('John');
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('Mary');
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('Alberto');
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('Juanita');
  FOR SELECT ID, VAL FROM VEC_F_Same_Name_Var
  ORDER BY ID ASC
  INTO :i_FOR1, :j_FOR1
  DO
  BEGIN
    summa = :summa || j_FOR1; 
  END
  i = 'Jon';
  summa = :summa || i;
END;