CREATE OR ALTER PACKAGE PACKAGE_OVERLOAD
SQL SECURITY DEFINER
AS BEGIN
/*
	[-unconvertible PROCEDURE Out_Screen(Var IN VARCHAR2)];

	[-unconvertible PROCEDURE Out_Screen(NM IN NUMBER)];

	[-unconvertible FUNCTION Add_One_Num(NM IN NUMBER, BM IN NUMBER) RETURN NUMBER];

	[-unconvertible FUNCTION Add_One_Num(M IN NUMBER, K IN VARCHAR2) RETURN VARCHAR];
*/
END /*PACKAGE_OVERLOAD*/;