CREATE OR REPLACE PACKAGE PACKAGE_OVERLOAD IS

	PROCEDURE Out_Screen(Var IN VARCHAR2);

	PROCEDURE Out_Screen(NM IN NUMBER);

	FUNCTION Add_One_Num(NM IN NUMBER, BM IN NUMBER) RETURN NUMBER;

	FUNCTION Add_One_Num(M IN NUMBER, K IN VARCHAR2) RETURN VARCHAR;

END PACKAGE_OVERLOAD;