CREATE /*EDITIONABLE*/ PACKAGE EDITIONABLE_PACKAGE
SQL SECURITY DEFINER
AS

END /*EDITIONABLE_PACKAGE*/;


CREATE /*NONEDITIONABLE*/ PACKAGE NONEDITIONABLE_PACKAGE
SQL SECURITY DEFINER
AS

END /*NONEDITIONABLE_PACKAGE*/;