/*CREATE OR ALTER PACKAGE PACKAGE_SHARING
[-unconvertible SHARING=METADATA]
SQL SECURITY DEFINER
AS BEGIN

END /*PACKAGE_SHARING*/;*/


/*CREATE OR ALTER PACKAGE PACKAGE_SHARING
[-unconvertible SHARING=NONE]
SQL SECURITY DEFINER
AS BEGIN

END /*PACKAGE_SHARING*/;*/