CREATE GLOBAL TEMPORARY TABLE VEC_P_For_With_While_and_When (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_For_With_While_and_When
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_P_For_With_While_and_When(VAL) VALUES ('John');
   INSERT INTO VEC_P_For_With_While_and_When(VAL) VALUES ('Mary');
   INSERT INTO VEC_P_For_With_While_and_When(VAL) VALUES ('Alberto');
   INSERT INTO VEC_P_For_With_While_and_When(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_P_For_With_While_and_When
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     IF (NOT(i_FOR1 != 4)) THEN LEAVE;
     IF (NOT(i_FOR1 != 2)) THEN CONTINUE;
     summa = :summa + i_FOR1; 
   END
END;