CREATE GLOBAL TEMPORARY TABLE VEC1_P_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC2_P_multiple (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_multiple
AS
  /* TYPE varray_t1 IS VARRAY(5) OF VARCHAR2(15); */
  /* vec1 varray_t1 := varray_t1('Olivia', 'William', 'Emma', 'Henry', 'Grace'); */
  /* TYPE nesttabl_t2 IS TABLE OF VARCHAR2(15); */
  /* vec2 nesttabl_t2 := nesttabl_t2('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa INTEGER = 0;
  DECLARE i_FOR1 INTEGER;
BEGIN
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Olivia');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('William');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Emma');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Henry');
  INSERT INTO VEC1_P_multiple(VAL) VALUES ('Grace');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('John');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('Mary');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('Alberto');
  INSERT INTO VEC2_P_multiple(VAL) VALUES ('Juanita');
  FOR SELECT ID FROM VEC1_P_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  FOR SELECT ID FROM VEC2_P_multiple
  ORDER BY ID ASC
  INTO :i_FOR1
  DO
  BEGIN
    summa = :summa + i_FOR1; 
  END
  WHILE (1=1) DO
  BEGIN
    i_FOR1 = 100;
    summa = :summa + i_FOR1; 
    LEAVE;
  END
END; 