CREATE GLOBAL TEMPORARY TABLE VEC_Varray_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

EXECUTE BLOCK 
AS
   /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
BEGIN
   INSERT INTO VEC_Varray_1(VAL) VALUES ('John');
   INSERT INTO VEC_Varray_1(VAL) VALUES ('Mary');
   INSERT INTO VEC_Varray_1(VAL) VALUES ('Alberto');
   INSERT INTO VEC_Varray_1(VAL) VALUES ('Juanita');
   FOR SELECT ID FROM VEC_Varray_1
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa + :i_FOR1; 
   END
END;