CREATE PACKAGE PACKAGE_NAME_CURRENT_USER SQL SECURITY CURRENT_USER AS BEGIN

END /*PACKAGE_NAME_CURRENT_USER*/;


CREATE OR ALTER PACKAGE PACKAGE_NAME_DEFINER SQL SECURITY DEFINER AS BEGIN

END /*PACKAGE_NAME_DEFINER*/;