CREATE IMMUTABLE TABLE immutable_transactions (
    transaction_id NUMBER GENERATED ALWAYS AS IDENTITY,
    amount NUMBER(10,2),
    description VARCHAR2(100)
) NO DROP UNTIL 1 DAYS IDLE
  NO DELETE UNTIL 16 DAYS AFTER INSERT
  INMEMORY;