CREATE OR REPLACE FUNCTION CALL_F
RETURN BOOLEAN
AUTHID DEFINER
IS
    EMP_NAME VARCHAR2(50);
    EMP_SALARY NUMBER;
BEGIN
    EXECUTE IMMEDIATE 'SELECT FIRST_NAME, SALARY FROM EMPLOYEES WHERE EMPLOYEE_ID = 142'
    INTO EMP_NAME, EMP_SALARY;
    RETURN TRUE;
END;