CREATE GLOBAL TEMPORARY TABLE VEC_Pack_From_Nested_table_PF_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_From_Nested_table_PP_From_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_From_Nested_table
AS BEGIN
   FUNCTION PF_From_Nested_table
   RETURNS VARCHAR(100);
   PROCEDURE PP_From_Nested_table; 
END; 

RECREATE PACKAGE BODY Pack_From_Nested_table
AS BEGIN
   FUNCTION PF_From_Nested_table
   RETURNS VARCHAR(100)
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
     DECLARE j_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_From_Nested_table_PF_From_Nested_table(VAL) VALUES ('Juanita');
     FOR SELECT ID, VAL FROM VEC_Pack_From_Nested_table_PF_From_Nested_table
     ORDER BY ID ASC
     INTO :i_FOR1, :j_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     RETURN summa;
   END

   PROCEDURE PP_From_Nested_table
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
     DECLARE j_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_From_Nested_table_PP_From_Nested_table(VAL) VALUES ('Juanita');
     FOR SELECT ID, VAL FROM VEC_Pack_From_Nested_table_PP_From_Nested_table
     ORDER BY ID ASC
     INTO :i_FOR1, :j_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
   END  
END;  