CREATE GLOBAL TEMPORARY TABLE VEC_P_For_With_Mutable_Index (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_For_With_Mutable_Index
AS
  /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa VARCHAR(100) = '';
   DECLARE i_FOR1 VARCHAR(15);
BEGIN
   INSERT INTO VEC_P_For_With_Mutable_Index(VAL) VALUES ('John');
   INSERT INTO VEC_P_For_With_Mutable_Index(VAL) VALUES ('Mary');
   INSERT INTO VEC_P_For_With_Mutable_Index(VAL) VALUES ('Alberto');
   INSERT INTO VEC_P_For_With_Mutable_Index(VAL) VALUES ('Juanita');
   FOR SELECT VAL FROM VEC_P_For_With_Mutable_Index
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     i_FOR1 = '---';
     summa = :summa || i_FOR1; 
   END
END;