CREATE GLOBAL TEMPORARY TABLE VEC_NestTable_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

EXECUTE BLOCK 
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa VARCHAR(100) = '';
   DECLARE i_FOR1 VARCHAR(15);
BEGIN
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('John');
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('Mary');
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('Alberto');
   INSERT INTO VEC_NestTable_1(VAL) VALUES ('Juanita');
   FOR SELECT VAL FROM VEC_NestTable_1
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     i_FOR1 = '---';
     summa = :summa || i_FOR1; 
   END
END;