CREATE GLOBAL TEMPORARY TABLE VEC_Pack_For_With_Mutable_Index_PF_For_With_Mutable_Index (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_For_With_Mutable_Index_PP_For_With_Mutable_Index (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_For_With_Mutable_Index
AS BEGIN
   FUNCTION PF_For_With_Mutable_Index
   RETURNS VARCHAR(100);
   PROCEDURE PP_For_With_Mutable_Index; 
END; 

RECREATE PACKAGE BODY Pack_For_With_Mutable_Index
AS BEGIN
   FUNCTION PF_For_With_Mutable_Index
   RETURNS VARCHAR(100)
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa VARCHAR(100) = '';
     DECLARE i_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PF_For_With_Mutable_Index(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PF_For_With_Mutable_Index(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PF_For_With_Mutable_Index(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PF_For_With_Mutable_Index(VAL) VALUES ('Juanita');
     FOR SELECT VAL FROM VEC_Pack_For_With_Mutable_Index_PF_For_With_Mutable_Index
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       i_FOR1 = '---';
       summa = :summa || i_FOR1; 
     END
     RETURN summa;
   END

   PROCEDURE PP_For_With_Mutable_Index
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa VARCHAR(100) = '';
     DECLARE i_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PP_For_With_Mutable_Index(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PP_For_With_Mutable_Index(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PP_For_With_Mutable_Index(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_For_With_Mutable_Index_PP_For_With_Mutable_Index(VAL) VALUES ('Juanita');
     FOR SELECT VAL FROM VEC_Pack_For_With_Mutable_Index_PP_For_With_Mutable_Index
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       i_FOR1 = '---';
       summa = :summa || i_FOR1; 
     END
   END  
END;  