EXECUTE BLOCK
    AS
    DECLARE VARIABLE LAST_NAME TYPE OF COLUMN EMPLOYEE.LAST_NAME;
    DECLARE VARIABLE JOB_ID TYPE OF COLUMN EMPLOYEE.EMP_NO;
BEGIN
FOR SELECT LAST_NAME, EMP_NO
    FROM EMPLOYEE
        INTO :LAST_NAME, :JOB_ID
    DO
    BEGIN

    END
END;