EXECUTE BLOCK
    AS
/*
    [-unconvertible RS-233573 DECLARE C1 (JOB VARCHAR(32765), MAX_WAGE NUMERIC(34, 8)) CURSOR FOR
    (SELECT * FROM EMPLOYEES
    WHERE JOB_ID = JOB
      AND SALARY > MAX_WAGE)];
*/
BEGIN
/*
    FOR PERSON IN C1('ST_CLERK', 3000)
    DO
        BEGIN

        END
*/
END;