/*ERROR: RED DATABASE DOES NOT SUPPORT CURSOR WITH PARAMETER*/
EXECUTE BLOCK
    AS
    /*CURSOR C1 (JOB VARCHAR2, MAX_WAGE NUMBER) IS
    SELECT LAST_NAME FROM EMPLOYEES
    WHERE JOB_ID = JOB
      AND SALARY > MAX_WAGE;*/
    DECLARE VARIABLE LAST_NAME TYPE OF COLUMN EMPLOYEE.LAST_NAME;
BEGIN
FOR SELECT LAST_NAME FROM EMPLOYEE
    WHERE JOB_ID = 'ST_CLERK'
      AND SALARY > 3000
        INTO :LAST_NAME
	DO BEGIN

    END
END;