CREATE PROCEDURE P_Grade_meaning1
    AS
DECLARE C1 CURSOR FOR
    (SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
    WHERE MANAGER_ID > 120);

    DECLARE C2 CURSOR FOR
    (SELECT LAST_NAME FROM EMPLOYEES
    WHERE MANAGER_ID > 120);


  DECLARE VARIABLE C1_ITEM TYPE OF TABLE C1;

  DECLARE VARIABLE C2_ITEM TYPE OF COLUMN EMPLOYEES.LAST_NAME;
BEGIN
OPEN C1;
FETCH C1 INTO C1_ITEM;
WHILE ( ROW_COUNT != 0 ) DO
BEGIN
        C1_ITEM.LAST_NAME = 'unknown';
FETCH C1 INTO C1_ITEM;
END
CLOSE C1;

OPEN C2;
FETCH C2 INTO C2_ITEM;
WHILE ( ROW_COUNT != 0 ) DO
BEGIN
        C2_ITEM = 'unknown';
FETCH C2 INTO C2_ITEM;
END
CLOSE C2;

END;