CREATE PROCEDURE P_Grade_meaning1
    IS
  CURSOR C1 IS
SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
WHERE MANAGER_ID > 120;

CURSOR C2 IS
SELECT LAST_NAME FROM EMPLOYEES
WHERE MANAGER_ID > 120;

BEGIN

FOR ITEM IN C1
      LOOP
        ITEM.LAST_NAME := 'unknown';
END LOOP;

FOR ITEM IN C2
      LOOP
        ITEM.LAST_NAME := 'unknown';
END LOOP;
END;