EXECUTE BLOCK
    AS
DECLARE C1 CURSOR  FOR
    (SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
    WHERE MANAGER_ID > 120
    ORDER BY LAST_NAME);

    DECLARE VARIABLE LAST_NAME TYPE OF COLUMN EMPLOYEE.LAST_NAME;
    DECLARE VARIABLE JOB_ID TYPE OF COLUMN EMPLOYEE.EMP_NO;
BEGIN
FOR SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
    WHERE MANAGER_ID > 120
    ORDER BY LAST_NAME
        INTO :LAST_NAME, :JOB_ID
	DO BEGIN
        LAST_NAME = 'MIKE';  -- REFER TO VARIABLE
    END
END;