EXECUTE BLOCK AS
   DECLARE C1 CURSOR FOR (SELECT T1.DEPT_NO, DEPARTMENT, BUDGET
   FROM DEPARTMENT T1,
        ( SELECT DEPT_NO, COUNT(*) AS STAFF
          FROM EMPLOYEE
          GROUP BY DEPT_NO
        ) T2
   WHERE (T1.DEPT_NO = T2.DEPT_NO) AND STAFF >= 5
   ORDER BY BUDGET);

    DECLARE VARIABLE DEPARTMENT_ID TYPE OF COLUMN DEPARTMENTS.DEPARTMENT_ID;
	DECLARE VARIABLE DEPARTMENT_NAME  TYPE OF COLUMN DEPARTMENTS.DEPARTMENT_NAME;
	DECLARE VARIABLE BUDGET TYPE OF COLUMN DEPARTMENTS.BUDGET;

BEGIN
FOR SELECT T1.DEPARTMENT_ID, DEPARTMENT_NAME, BUDGET
     FROM DEPARTMENT T1,
          ( SELECT DEPT_NO, COUNT(*) AS STAFF
            FROM EMPLOYEE
            GROUP BY DEPT_NO
          ) T2
     WHERE (T1.DEPARTMENT_ID = T2.DEPARTMENT_ID) AND STAFF >= 5
     ORDER BY BUDGET
         INTO :DEPARTMENT_ID, :DEPARTMENT_NAME, :BUDGET
	DO BEGIN

    END
END;