EXECUTE BLOCK
    AS

    DECLARE C1 CURSOR FOR
    (SELECT T1.DEPARTMENT_ID, DEPARTMENT_NAME, BUDGET
        FROM DEPARTMENTS T1,
     ( SELECT DEPARTMENT_ID, COUNT(*) AS STAFF
       FROM EMPLOYEES
       GROUP BY DEPARTMENT_ID
     ) T2
    WHERE (T1.DEPARTMENT_ID = T2.DEPARTMENT_ID) AND STAFF >= 5
    ORDER BY STAFF);

  DECLARE VARIABLE C1_DEPT TYPE OF TABLE C1;
BEGIN

    OPEN C1;
    FETCH C1 INTO C1_DEPT;
    WHILE ( ROW_COUNT != 0 ) DO
BEGIN

    FETCH C1 INTO C1_DEPT;
    END
    CLOSE C1;

END;
