DECLARE
    CURSOR C1 IS
    SELECT T1.DEPARTMENT_ID, DEPARTMENT_NAME, BUDGET
    FROM DEPARTMENTS T1,
         ( SELECT DEPARTMENT_ID, COUNT(*) AS STAFF
           FROM EMPLOYEES
           GROUP BY DEPARTMENT_ID
         ) T2
    WHERE (T1.DEPARTMENT_ID = T2.DEPARTMENT_ID) AND STAFF >= 5
    ORDER BY STAFF;

BEGIN
FOR DEPT IN C1
    LOOP

    END LOOP;
END;