CREATE OR ALTER PACKAGE Pack_Grade_meaning1
AS BEGIN
   FUNCTION PF_Grade_meaning1 (degree INTEGER)
   RETURN BOOLEAN;
   PROCEDURE PP_Grade_meaning1;
END /*PACK_GRADE_MEANING1*/;

RECREATE PACKAGE BODY Pack_Grade_meaning1
AS BEGIN
    FUNCTION PF_Grade_meaning1 (degree INTEGER)
    RETURNS BOOLEAN
    AS

    DECLARE VARIABLE ITEM_TEMP_CURSOR CURSOR FOR (SELECT LAST_NAME, EMP_NO
                FROM EMPLOYEE);

   DECLARE VARIABLE ITEM TYPE OF TABLE ITEM_TEMP_CURSOR;
    BEGIN
    FOR (SELECT LAST_NAME, EMP_NO
                    FROM EMPLOYEE
                  ) INTO ITEM DO
        BEGIN

        END
    RETURN TRUE;
    END

    PROCEDURE PP_Grade_meaning1
    AS

    DECLARE VARIABLE ITEM_TEMP_CURSOR CURSOR FOR (SELECT LAST_NAME, EMP_NO
                    FROM EMPLOYEE);

    DECLARE VARIABLE ITEM TYPE OF TABLE ITEM_TEMP_CURSOR;
    BEGIN
    FOR (
                    SELECT LAST_NAME, EMP_NO
                    FROM EMPLOYEE
                  ) INTO ITEM DO
        BEGIN


        END
    END
END /*PACK_GRADE_MEANING1*/;