/*CREATE TABLE "ACCOUNTS"
   (	"ID" NUMERIC(34, 8),
	"ACCOUNT_NUMBER" NUMERIC(34, 8),
	"CUSTOMER_ID" NUMERIC(34, 8),
	"BALANCE" NUMERIC(34, 8),
	"BRANCH_ID" NUMERIC(34, 8),
	"REGION" VARCHAR(2 ),
	"STATUS" VARCHAR(1 )
   )
  TABLESPACE "SYSAUX"
  [-unconvertible PARTITION BY LIST ("REGION")
  SUBPARTITION BY LIST ("STATUS")
 (PARTITION "P_NORTHWEST"  VALUES ('OR', 'WA')
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 ( SUBPARTITION "P_NW_BAD"  VALUES ('B') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_NW_AVERAGE"  VALUES ('A') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_NW_GOOD"  VALUES ('G') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ) ,
 PARTITION "P_SOUTHWEST"  VALUES ('AZ', 'UT', 'NM')
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 ( SUBPARTITION "P_SW_BAD"  VALUES ('B') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_SW_AVERAGE"  VALUES ('A') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_SW_GOOD"  VALUES ('G') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ))] ;*/