CREATE TABLE "TESTS_TABLES_PARTITION"."ACCOUNTS"
   (	"ID" NUMBER,
	"ACCOUNT_NUMBER" NUMBER,
	"CUSTOMER_ID" NUMBER,
	"BALANCE" NUMBER,
	"BRANCH_ID" NUMBER,
	"REGION" VARCHAR2(2 BYTE),
	"STATUS" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
  PARTITION BY LIST ("REGION")
  SUBPARTITION BY LIST ("STATUS")
 (PARTITION "P_NORTHWEST"  VALUES ('OR', 'WA')
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 ( SUBPARTITION "P_NW_BAD"  VALUES ('B') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_NW_AVERAGE"  VALUES ('A') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_NW_GOOD"  VALUES ('G') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ) ,
 PARTITION "P_SOUTHWEST"  VALUES ('AZ', 'UT', 'NM')
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 ( SUBPARTITION "P_SW_BAD"  VALUES ('B') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_SW_AVERAGE"  VALUES ('A') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS ,
  SUBPARTITION "P_SW_GOOD"  VALUES ('G') SEGMENT CREATION DEFERRED
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX"
 NOCOMPRESS )) ;