CREATE OR REPLACE PACKAGE CALL_PCKG
AS
    PROCEDURE TEST_P;
    FUNCTION TEST_F RETURN BOOLEAN;
END;

CREATE OR REPLACE PACKAGE BODY CALL_PCKG
AS
    FUNCTION TEST_F
        RETURN BOOLEAN
    IS
        VALUE_OUT NUMBER;
        STMT VARCHAR2(50);
    BEGIN
        VALUE_OUT := 0;
        STMT := 'BEGIN OUT_P(:A); END;';
        EXECUTE IMMEDIATE STMT USING IN VALUE_OUT;
        RETURN TRUE;
    END;

    PROCEDURE TEST_P
    IS
        VALUE_OUT NUMBER;
        STMT VARCHAR2(50);
    BEGIN
        VALUE_OUT := 0;
        STMT := 'BEGIN OUT_P(:A); END;';
        EXECUTE IMMEDIATE STMT USING IN VALUE_OUT;
    END;
END;