/*CREATE TRIGGER COMP_TEST
[-unconvertible RS-228297 FOR INSERT OR UPDATE OR DELETE ON EMP_TEST
     SQL SECURITY DEFINER
AS
COMPOUND TRIGGER
    AFTER STATEMENT IS BEGIN

    END AFTER STATEMENT;
END];*/