/*CREATE TRIGGER "COMP_TEST"
[-unconvertible RS-228297 FOR INSERT OR UPDATE OR DELETE
    ON V
     SQL SECURITY DEFINER
AS
COMPOUND TRIGGER
    INSTEAD OF EACH ROW IS BEGIN

    END INSTEAD OF EACH ROW;
END];*/