CREATE /*EDITIONABLE*/ PACKAGE BODY EDITIONABLE_PACKAGE_BODY AS

END /*EDITIONABLE_PACKAGE_BODY*/;


CREATE /*NONEDITIONABLE*/ PACKAGE BODY NONEDITIONABLE_PACKAGE_BODY AS

END /*NONEDITIONABLE_PACKAGE_BODY*/;