CREATE FUNCTION F_Grade_meaning1
RETURN BOOLEAN
IS
  CURSOR C1 IS
    SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
    WHERE MANAGER_ID > 120
    ORDER BY LAST_NAME;
BEGIN
    FOR ITEM IN C1
      LOOP
        NULL;
    END LOOP;
RETURN TRUE;
END;