CREATE OR ALTER PACKAGE Pack_Grade_meaning1
AS BEGIN
/*
   FUNCTION PF_Grade_meaning1 (degree INTEGER)
   RETURN BOOLEAN;
   PROCEDURE PP_Grade_meaning1;

    [-unconvertible RS-233552 DECLARE BOOKS_CUR RETURN TYPE OF TABLE BOOKS];

    [-unconvertible RS-233552 DECLARE C1 CURSOR FOR
        (SELECT LAST_NAME, JOB_ID FROM EMPLOYEES
        WHERE MANAGER_ID > 120
        ORDER BY LAST_NAME)];
*/
END /*PACK_GRADE_MEANING1*/;

RECREATE PACKAGE BODY Pack_Grade_meaning1
AS BEGIN
/*
    [-unconvertible RS-233552 DECLARE BOOKS_CUR
        RETURN TYPE OF TABLE BOOKS
            CURSOR FOR
    (SELECT BOOK_NAME
    FROM BOOKS)];

    FUNCTION PF_Grade_meaning1 (degree INTEGER)
           RETURNS BOOLEAN
           AS
    BEGIN
    OPEN C1;
    FETCH C1 INTO C1_ITEM;
    WHILE ( ROW_COUNT != 0 ) DO
        BEGIN

        FETCH C1 INTO C1_ITEM;
        END
    CLOSE C1;

    RETURN TRUE;
    END

    PROCEDURE PP_Grade_meaning1
    AS
        DECLARE VARIABLE BOOKS_CUR_ITEM TYPE OF COLUMN BOOKS.BOOK_NAME;
    BEGIN
    OPEN BOOKS_CUR;
    FETCH BOOKS_CUR INTO BOOKS_CUR_ITEM;
    WHILE ( ROW_COUNT != 0 ) DO
    BEGIN

        FETCH BOOKS_CUR INTO BOOKS_CUR_ITEM;
    END
    CLOSE BOOKS_CUR;

    END
 */
END /*PACK_GRADE_MEANING1*/;