CREATE PROCEDURE PROCEDURE_NAME
SQL SECURITY DEFINER
    AS
    DECLARE v_old_pages NUMERIC(34, 8);
BEGIN
    UPDATE "BOOKS"
        SET "PAGE_COUNT" = "PAGE_COUNT" + 20
        WHERE "PAGE_COUNT" >  650
    RETURNING OLD.PAGE_COUNT INTO :v_old_pages;
END;