CREATE PROCEDURE PROCEDURE_NAME
    IS
    v_old_pages NUMBER;
BEGIN
    UPDATE "HR"."BOOKS"
        SET "PAGE_COUNT" = "PAGE_COUNT" + 20
        WHERE "PAGE_COUNT" > 650
    RETURNING NEW PAGE_COUNT INTO v_old_pages;
END;