CREATE PROCEDURE PROCEDURE_NAME
SQL SECURITY DEFINER
    AS
    DECLARE v_new_pages NUMERIC(34, 8);
    DECLARE v_title VARCHAR(100);
BEGIN
    UPDATE "BOOKS"
        SET "PAGE_COUNT" = "PAGE_COUNT" + 20
        WHERE "PAGE_COUNT" > 800
    RETURNING "PAGE_COUNT", "TITLE" INTO :v_new_pages, :v_title;
END;