CREATE GLOBAL TEMPORARY TABLE VEC_Pack_Index_With_Label_PF_Index_With_Label (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_Index_With_Label_PP_Index_With_Label (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_Index_With_Label
AS BEGIN
   FUNCTION PF_Index_With_Label
   RETURNS VARCHAR(100);
   PROCEDURE PP_Index_With_Label; 
END; 

RECREATE PACKAGE BODY Pack_Index_With_Label
AS BEGIN
   FUNCTION PF_Index_With_Label
   RETURNS VARCHAR(100)
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
     DECLARE j_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_Index_With_Label_PF_Index_With_Label(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_Index_With_Label_PF_Index_With_Label(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_Index_With_Label_PF_Index_With_Label(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_Index_With_Label_PF_Index_With_Label(VAL) VALUES ('Juanita');
     forlabel:
     FOR SELECT ID, VAL FROM VEC_Pack_Index_With_Label_PF_Index_With_Label
     ORDER BY ID ASC
     INTO :i_FOR1, :j_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
     RETURN summa;
   END

   PROCEDURE PP_Index_With_Label
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
     DECLARE j_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_Index_With_Label_PP_Index_With_Label(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_Index_With_Label_PP_Index_With_Label(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_Index_With_Label_PP_Index_With_Label(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_Index_With_Label_PP_Index_With_Label(VAL) VALUES ('Juanita');
     forlabel:
     FOR SELECT ID, VAL FROM VEC_Pack_Index_With_Label_PP_Index_With_Label
     ORDER BY ID ASC
     INTO :i_FOR1, :j_FOR1
     DO
     BEGIN
       summa = :summa + i_FOR1; 
     END
   END  
END;  