CREATE PROCEDURE PROCEDURE_NAME
SQL SECURITY DEFINER
    AS
    DECLARE v_new_pages NUMERIC(34, 8);
    DECLARE v_title VARCHAR(100);
BEGIN
    DELETE FROM  "BOOKS"
    WHERE "PAGE_COUNT" > 200
        RETURNING "PAGE_COUNT", "TITLE" INTO :v_new_pages, :v_title;
END;