SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(month FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(day FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(HOUR FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(second FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(TIMEZONE_HOUR FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

SELECT EXTRACT(TIMEZONE_MINUTE FROM CURRENT_TIMESTAMP) FROM RDB$DATABASE;

/*
SELECT [-unconvertible EXTRACT(TIMEZONE_ABBR FROM CURRENT_TIMESTAMP)] FROM DUAL;
*/
/*
SELECT [-unconvertible EXTRACT(TIMEZONE_REGION FROM CURRENT_TIMESTAMP)] FROM DUAL;
*/

SELECT EXTRACT(HOUR FROM cast('1999-01-01 10:00:00 -08:00' as TIMESTAMP)) FROM RDB$DATABASE;

/*
SELECT EXTRACT(YEAR FROM [-unconvertible INTERVAL '123-06' YEAR(3) TO MONTH]) FROM DUAL;
*/
/*
SELECT EXTRACT(month FROM [-unconvertible INTERVAL '123-06' YEAR(3) TO MONTH]) FROM DUAL;
*/
/*
SELECT EXTRACT(day FROM [-unconvertible INTERVAL '1 3' DAY(3) TO HOUR]) FROM DUAL;
*/