SELECT EXTRACT(YEAR FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(month FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(day FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(HOUR FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(second FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(TIMEZONE_HOUR FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(TIMEZONE_MINUTE FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(TIMEZONE_ABBR FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(TIMEZONE_REGION FROM CURRENT_TIMESTAMP) FROM DUAL;

SELECT EXTRACT(HOUR FROM TIMESTAMP '1999-01-01 10:00:00 -08:00') FROM DUAL;

SELECT EXTRACT(YEAR FROM INTERVAL '123-06' YEAR(3) TO MONTH) FROM DUAL;

SELECT EXTRACT(month FROM INTERVAL '123-06' YEAR(3) TO MONTH) FROM DUAL;

SELECT EXTRACT(day FROM INTERVAL '1 3' DAY(3) TO HOUR) FROM DUAL;
