RECREATE FUNCTION MONTHS_BETWEEN (date1 DATE, date2 DATE) 
RETURNS DOUBLE PRECISION 
AS
  DECLARE v_years   NUMERIC;
  DECLARE v_months  NUMERIC;
  DECLARE v_days    NUMERIC;
BEGIN
  IF ((LAST_DAY(OF MONTH FROM date1) = CAST(date1 AS DATE FORMAT 'YYYY-MM-DD'))
     AND (LAST_DAY(OF MONTH FROM date2) = CAST(date2 AS DATE FORMAT 'YYYY-MM-DD')))
  THEN 
    v_days = 0;
  ELSE 
    v_days = EXTRACT(DAY FROM date1) - EXTRACT(DAY FROM date2);

  v_years = EXTRACT(YEAR FROM date1) - EXTRACT(YEAR FROM date2);
  v_months = EXTRACT(MONTH FROM date1) - EXTRACT(MONTH FROM date2);
    
  RETURN v_years * 12 + v_months + v_days / 31.0000000000;
END;

SELECT MONTHS_BETWEEN(CAST('02-02-1995' AS DATE FORMAT 'MM-DD-YYYY'), CAST('01-01-1995' AS DATE FORMAT 'MM-DD-YYYY') ) FROM RDB$DATABASE;

SELECT MONTHS_BETWEEN(CAST('03-31-1995' AS DATE FORMAT 'MM-DD-YYYY'), CAST('04-10-1995' AS DATE FORMAT 'MM-DD-YYYY') ) FROM RDB$DATABASE;

SELECT MONTHS_BETWEEN(CAST('04-10-1996' AS DATE FORMAT 'MM-DD-YYYY'), CAST('04-10-1995' AS DATE FORMAT 'MM-DD-YYYY') ) FROM RDB$DATABASE;

SELECT MONTHS_BETWEEN(CAST('04-04-2025' AS DATE FORMAT 'MM-DD-YYYY'), CAST('10-31-1995' AS DATE FORMAT 'MM-DD-YYYY') ) FROM RDB$DATABASE;

SELECT MONTHS_BETWEEN(CAST('04-30-2025' AS DATE FORMAT 'MM-DD-YYYY'), CAST('01-31-1995' AS DATE FORMAT 'MM-DD-YYYY') ) FROM RDB$DATABASE;
