  CREATE TABLE "COUNTRIES_DEMO" (
    "COUNTRY_ID" CHAR(2 BYTE) CONSTRAINT "COUNTRY_ID_NN_DEMO" NOT NULL ENABLE,
	"COUNTRY_NAME" VARCHAR2(40 BYTE), 
	"CURRENCY_NAME" VARCHAR2(25 BYTE), 
	"CURRENCY_SYMBOL" VARCHAR2(3 BYTE), 
	"REGION" VARCHAR2(15 BYTE), 
	 CONSTRAINT "COUNTRY_C_ID_PK_DEMO" PRIMARY KEY ("COUNTRY_ID") ENABLE
  ) SEGMENT CREATION DEFERRED
  ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE( INITIAL 16384
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSAUX" 
  PCTTHRESHOLD 2 INCLUDING "COUNTRY_NAME" OVERFLOW
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 LOGGING
  TABLESPACE "SYSAUX";
