CREATE TABLE employees (
    employee_id NUMBER
)
STORAGE (
    INITIAL 1M
    NEXT 1M
    MINEXTENTS 1
    MAXEXTENTS UNLIMITED
    PCTINCREASE 0
    FREELISTS 2
    FREELIST GROUPS 1
    BUFFER_POOL KEEP
    FLASH_CACHE KEEP
    CELL_FLASH_CACHE NONE
);