CREATE GLOBAL TEMPORARY TABLE VEC_F_For_With_When (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_For_With_When
RETURNS VARCHAR(100)
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa VARCHAR(100) = '';
   DECLARE i_FOR1 VARCHAR(15);
BEGIN
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('John');
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('Mary');
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('Alberto');
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('Juanita');
   FOR SELECT VAL FROM VEC_F_For_With_When
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     IF (NOT(i_FOR1 != 'Mary')) THEN CONTINUE;
     summa = :summa || i_FOR1; 
   END
END;