CREATE TRIGGER T_Null_In_If
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
  i PLS_INTEGER := 10;
  j PLS_INTEGER;
BEGIN
  IF i = 2 THEN
    NULL;
  ELSIF i = 3 THEN
    NULL;
  ELSIF i = 4 THEN
    j := 10;
    NULL;
  ELSE NULL;
  END IF;
  NULL;
END;