CREATE FUNCTION division (m DOUBLE PRECISION, n DOUBLE PRECISION)
    RETURNS DOUBLE PRECISION
AS
BEGIN
RETURN cast(m as DOUBLE PRECISION)/cast(n as DOUBLE PRECISION);
END;

SELECT division(11,4) FROM RDB$DATABASE;