CREATE TRIGGER T_Continue_Label_When
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
DECLARE
  x NUMBER := 0;
BEGIN
  <<while1>>
  WHILE (x != 5) LOOP
    x := x + 1;
    CONTINUE while1 WHEN x < 3;
  END LOOP;
END;