CREATE GLOBAL TEMPORARY TABLE VEC_P_From_Reverse_Nested_table (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_From_Reverse_Nested_table
AS
  /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
   DECLARE j_FOR1 VARCHAR(15);
BEGIN
   INSERT INTO VEC_P_From_Reverse_Nested_table(VAL) VALUES ('John');
   INSERT INTO VEC_P_From_Reverse_Nested_table(VAL) VALUES ('Mary');
   INSERT INTO VEC_P_From_Reverse_Nested_table(VAL) VALUES ('Alberto');
   INSERT INTO VEC_P_From_Reverse_Nested_table(VAL) VALUES ('Juanita');
   FOR SELECT ID, VAL FROM VEC_P_From_Reverse_Nested_table
   ORDER BY ID DESC
   INTO :i_FOR1, :j_FOR1
   DO
   BEGIN
     summa = :summa + i_FOR1; 
   END
END;