CREATE GLOBAL TEMPORARY TABLE VEC_F_Explicit_Index (
    K INTEGER,
    VAL INTEGER,
    CONSTRAINT PK_VEC_F_Explicit_Index PRIMARY KEY (K)
);

CREATE FUNCTION F_Explicit_Index
RETURNS INTEGER
AS
  /* TYPE intvec_t IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER; */
  /* vec intvec_t := intvec_t(3 => 10, 1 => 11, 100 => 34); */
  DECLARE summa NUMERIC(5,1) = 0;
  DECLARE n_FOR1 NUMERIC(5,1);
BEGIN
  UPDATE OR INSERT INTO VEC_F_Explicit_Index VALUES (3, 10);
  UPDATE OR INSERT INTO VEC_F_Explicit_Index VALUES (1, 11);
  UPDATE OR INSERT INTO VEC_F_Explicit_Index VALUES (100, 34);
  FOR SELECT VAL FROM VEC_F_Explicit_Index
  ORDER BY K ASC
  INTO :n_FOR1
  DO
  BEGIN
    summa = summa + n_FOR1; 
  END
  RETURN summa; -- 55
END; 