CREATE FUNCTION CALLING_FUNCTION_NAME
RETURNS VARCHAR(32765)
SQL SECURITY DEFINER
AS
    DECLARE in_value VARCHAR(50);
BEGIN
	in_value = 'in_value';
    EXECUTE PROCEDURE PROCEDURE_NAME(:in_value);
END;