CREATE PACKAGE CALLING_PACKAGE
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURNS VARCHAR(32765);
END /*CALLING_PACKAGE*/;

CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURNS VARCHAR(32765)
    AS
   	    DECLARE in_value VARCHAR(50);
    BEGIN
		in_value = 'in_value';
        EXECUTE PROCEDURE PROCEDURE_NAME(:in_value);
    END
END /*CALLING_PACKAGE*/;
----------------------------------------------
CREATE PACKAGE CALLING_PACKAGE
SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
END /*CALLING_PACKAGE*/;

CREATE PACKAGE BODY CALLING_PACKAGE
AS BEGIN
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    AS
        DECLARE in_value VARCHAR(50);
    BEGIN
		in_value = 'in_value';
        EXECUTE PROCEDURE PROCEDURE_NAME(:in_value);
    END
END /*CALLING_PACKAGE*/;