CREATE PACKAGE CALLING_PACKAGE
AS
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE RETURN VARCHAR2;
END CALLING_PACKAGE;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
   FUNCTION FUNCTION_NAME_INSIDE_PACKAGE
   RETURN VARCHAR2
   IS
        in_value VARCHAR2(50);
    BEGIN
       in_value := 'in_value';
        PROCEDURE_NAME(in_value);
    END;
END CALLING_PACKAGE;
----------------------------------------------
CREATE PACKAGE CALLING_PACKAGE
AS
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE;
END CALLING_PACKAGE;

CREATE PACKAGE BODY CALLING_PACKAGE
AS
    PROCEDURE PROCEDURE_NAME_IN_PACKAGE
    IS
        in_value VARCHAR2(50);
    BEGIN
        in_value := 'in_value';
        PROCEDURE_NAME(in_value);
    END;
END CALLING_PACKAGE;