/*CREATE FUNCTION SHELL(CMD IN VARCHAR2)
RETURN INTEGER
SQL SECURITY DEFINER
AS
[-unconvertible LANGUAGE C
LIBRARY EXTPROCSHELL_LIB
NAME "EXTPROCSHELL"
PARAMETERS (CMD STRING, RETURN INT)];*/

/*CREATE FUNCTION SHELL(CMD IN VARCHAR2)
    RETURN INTEGER
        AS
SQL SECURITY DEFINER
[-unconvertible EXTERNAL                       -- using external clause
LIBRARY EXTPROCSHELL_LIB
NAME "EXTPROCSHELL"
PARAMETERS (CMD STRING, RETURN INT)];*/