CREATE FUNCTION BETWNSTR (
    STRING_IN      VARCHAR(32765),
    START_IN       INTEGER,
    END_IN         INTEGER
)
    RETURNS VARCHAR(32765)
    DETERMINISTIC
    SQL SECURITY DEFINER
AS
BEGIN

END;