SELECT ASCII(NULL) FROM DUAL;

SELECT ASCII('') FROM DUAL;

SELECT ASCII('B') FROM DUAL;

SELECT ASCII('CAT') FROM DUAL;

SELECT ASCII('cat') FROM DUAL;

SELECT ASCII('dog') FROM DUAL;

SELECT ASCII(':') FROM DUAL;