CREATE EXCEPTION CUSTOM_EXCEPTION 'error';

CREATE FUNCTION POSITION_CUSTOM (str VARCHAR(8191), substr VARCHAR(8191), p INTEGER = 1, occurrence INTEGER = 1) 
RETURNS VARCHAR(8191) 
AS
BEGIN
    IF (occurrence <= 0) THEN
      EXCEPTION CUSTOM_EXCEPTION('Argument occurrence is out of range.');
    IF (p = 0) THEN
      RETURN 0;
    IF (p > 0) THEN
      RETURN POSITION(substr, str, p, occurrence);
    IF (p < 0) THEN
      RETURN CHAR_LENGTH(str) - POSITION(REVERSE(substr), REVERSE(str), ABS(p), occurrence) - CHAR_LENGTH(substr) + 2;
END;


SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', 3, 2) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR') FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'IR') FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', 3) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', 3, 20) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', 30, 2) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', -3) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', -1) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', -1, 2) FROM RDB$DATABASE;

SELECT POSITION_CUSTOM('CORPORATE FLOOR', 'OR', -1, 3) FROM RDB$DATABASE;

/*
SELECT [-unconvertible INSTRB('CORPORATE FLOOR','OR', 3, 2)] FROM DUAL;
*/
/*
SELECT [-unconvertible INSTRC('CORPORATE FLOOR','OR', 3, 2)] FROM DUAL;
*/
/*
SELECT [-unconvertible INSTR2('CORPORATE FLOOR','OR', 3, 2)] FROM DUAL;
*/
/*
SELECT [-unconvertible INSTR4('CORPORATE FLOOR','OR', 3, 2)] FROM DUAL;
*/