SELECT DECODE('CANDIDE', '', NULL, CHAR_LENGTH('CANDIDE')) FROM RDB$DATABASE;
SELECT DECODE('Рукав', '', NULL, CHAR_LENGTH('Рукав')) FROM RDB$DATABASE;
SELECT DECODE('', '', NULL, CHAR_LENGTH('')) FROM RDB$DATABASE;

SELECT DECODE('CANDIDE', '', NULL, OCTET_LENGTH('CANDIDE')) FROM RDB$DATABASE;
SELECT DECODE('Рукав', '', NULL, OCTET_LENGTH('Рукав')) FROM RDB$DATABASE;
SELECT DECODE('', '', NULL, CHAR_LENGTH('')) FROM RDB$DATABASE;

/*
SELECT [-unconvertible LENGTHC('CANDIDE')] FROM DUAL;
*/
/*
SELECT [-unconvertible LENGTH2('CANDIDE')] FROM DUAL;
*/
/*
SELECT [-unconvertible LENGTH4('CANDIDE')] FROM DUAL;
*/