SELECT DECODE('CANDIDE'||'R', 'R', NULL, LOWER('CANDIDE')) FROM RDB$DATABASE;
SELECT DECODE('Рукав'||'R', 'R', NULL, LOWER('Рукав')) FROM RDB$DATABASE;
SELECT DECODE(''||'R', 'R', NULL, LOWER('')) FROM RDB$DATABASE;