SELECT REPLACE(NULLIF('JACK and JUE',''), COALESCE('J', ''), COALESCE('BL', '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF('JACK and JUE', ''), COALESCE(NULL, ''), COALESCE('BL', '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF('JACK and JUE', ''), COALESCE('', ''), COALESCE('BL', '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF('JACK and JUE',''),COALESCE('J', ''), COALESCE(NULL, '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF('JACK and JUE', ''),COALESCE('J', ''), COALESCE('', '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF(NULL, ''),COALESCE('J', ''), COALESCE('BL', '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF('',''),COALESCE('J', ''),COALESCE('BL', '')) FROM RDB$DATABASE;

SELECT REPLACE(NULLIF('JACK and JUE',''),COALESCE('J', ''),COALESCE('','')) FROM RDB$DATABASE;

