SELECT REPLACE('JACK and JUE','J','BL') FROM DUAL;

SELECT REPLACE('JACK and JUE', NULL ,'BL') FROM DUAL;

SELECT REPLACE('JACK and JUE', '' ,'BL') FROM DUAL;

SELECT REPLACE('JACK and JUE','J', NULL) FROM DUAL;

SELECT REPLACE('JACK and JUE','J', '') FROM DUAL;

SELECT REPLACE(NULL,'J','BL') FROM DUAL;

SELECT REPLACE('','J','BL') FROM DUAL;

SELECT REPLACE('JACK and JUE','J') FROM DUAL;