CREATE FUNCTION SUBSTR_CUSTOM (str1 VARCHAR(32765), pos INTEGER, len INTEGER = 32765) 
RETURNS VARCHAR(32765) 
AS
BEGIN
  IF (str1||'R' = 'R' OR len <= 0) THEN
    RETURN NULL;
  IF (str1 = NULL OR pos = NULL OR len = NULL) THEN
    RETURN NULL;
  IF (pos = 0) THEN
     pos = 1;
  IF (pos < 0) THEN 
     IF (ABS(pos) > CHAR_LENGTH(str1)) THEN 
       RETURN NULL;
     ELSE
       pos = CHAR_LENGTH(str1) + pos + 1;
  IF (pos > 0) THEN  
    RETURN SUBSTRING(str1 FROM pos FOR len);
  RETURN NULL;  -- не должно возникать
END;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',3) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',3,4) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',3,0) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',-5) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',-5,4) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',-5,0) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',0) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',0,4) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',3,100) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('',3) FROM RDB$DATABASE;

SELECT SUBSTR_CUSTOM('ABCDEFGHIJK',-50) FROM RDB$DATABASE;

/*
SELECT SUBSTRB('ABCDEFG',5,4) FROM DUAL;
*/
/*
SELECT SUBSTRC('ABCDEFG',5,4) FROM DUAL;
*/
/*
SELECT SUBSTR2('ABCDEFG',5,4) FROM DUAL;
*/
/*
SELECT SUBSTR4('ABCDEFG',5,4) FROM DUAL;
*/
