SELECT TRIM('  Hello   ') FROM RDB$DATABASE;
SELECT TRIM(LEADING FROM '  Hello   ') FROM RDB$DATABASE;
SELECT TRIM(TRAILING FROM '  Hello   ') FROM RDB$DATABASE;
SELECT TRIM(BOTH FROM '  Hello   ') FROM RDB$DATABASE;
SELECT TRIM('*' FROM '**Hello*') FROM RDB$DATABASE;
SELECT TRIM(LEADING '*' FROM '**Hello*') FROM RDB$DATABASE;
SELECT TRIM(TRAILING '*' FROM '**Hello*') FROM RDB$DATABASE;
SELECT TRIM(BOTH '*' FROM '**Hello*') FROM RDB$DATABASE;