SELECT DECODE('CANDIDE'||'R', 'R', NULL, UPPER('CANDIDE')) FROM RDB$DATABASE;
SELECT DECODE('Рукав'||'R', 'R', NULL, UPPER('Рукав')) FROM RDB$DATABASE;
SELECT DECODE(''||'R', 'R', NULL, UPPER('')) FROM RDB$DATABASE;