CREATE PACKAGE PackF_Sqlrowcount
SQL SECURITY DEFINER
AS BEGIN
   FUNCTION PF_Sqlrowcount 
   RETURNS VARCHAR(32765);
END;

CREATE PACKAGE BODY PackF_Sqlrowcount
AS BEGIN
   FUNCTION PF_Sqlrowcount
   RETURNS VARCHAR(32765)
   AS
     DECLARE tmp INTEGER;
   BEGIN
     tmp = ROW_COUNT;
     UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
     tmp = ROW_COUNT;
     RETURN '';
   END
END;