CREATE PACKAGE PackP_Sqlrowcount
SQL SECURITY DEFINER
AS BEGIN
    PROCEDURE PP_Sqlrowcount;
END;

CREATE PACKAGE BODY PackP_Sqlrowcount
AS
BEGIN
    PROCEDURE PP_Sqlrowcount
    AS
      DECLARE tmp INTEGER;
    BEGIN
      tmp = ROW_COUNT;
      UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
      tmp = ROW_COUNT;
    END
END;