CREATE FUNCTION F_Sqlrowcount
RETURN VARCHAR2
IS
  tmp PLS_INTEGER;
BEGIN
  tmp := SQL%ROWCOUNT;
  UPDATE employees SET SALARY = SALARY * 1.1 WHERE SALARY <= 60000;
  tmp := SQL%ROWCOUNT;
  RETURN '';
END;