/* Процедура */
CREATE GLOBAL TEMPORARY TABLE VEC_P_Same_Name_Var (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_Same_Name_Var
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
  /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa VARCHAR(100) = '';
  DECLARE i VARCHAR(15);
  DECLARE j VARCHAR(15);
  DECLARE i_FOR1 INTEGER;
  DECLARE j_FOR1 VARCHAR(15);
BEGIN
  INSERT INTO VEC_P_Same_Name_Var(VAL) VALUES ('John');
  INSERT INTO VEC_P_Same_Name_Var(VAL) VALUES ('Mary');
  INSERT INTO VEC_P_Same_Name_Var(VAL) VALUES ('Alberto');
  INSERT INTO VEC_P_Same_Name_Var(VAL) VALUES ('Juanita');
  FOR SELECT ID, VAL FROM VEC_P_Same_Name_Var
  ORDER BY ID ASC
  INTO :i_FOR1, :j_FOR1
  DO
  BEGIN
    summa = :summa || j_FOR1; 
  END
  i = 'Jon';
  summa = :summa || i;
END;

/* Функция */
CREATE GLOBAL TEMPORARY TABLE VEC_F_Same_Name_Var (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_Same_Name_Var
RETURNS VARCHAR(100)
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
  /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa VARCHAR(100) = '';
  DECLARE i VARCHAR(15);
  DECLARE j VARCHAR(15);
  DECLARE i_FOR1 INTEGER;
  DECLARE j_FOR1 VARCHAR(15);
BEGIN
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('John');
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('Mary');
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('Alberto');
  INSERT INTO VEC_F_Same_Name_Var(VAL) VALUES ('Juanita');
  FOR SELECT ID, VAL FROM VEC_F_Same_Name_Var
  ORDER BY ID ASC
  INTO :i_FOR1, :j_FOR1
  DO
  BEGIN
    summa = :summa || j_FOR1; 
  END
  i = 'Jon';
  summa = :summa || i;
END;

/* Пакет */
CREATE GLOBAL TEMPORARY TABLE VEC_Pack_Same_Name_Var_PF_Same_Name_Var (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_Same_Name_Var_PP_Same_Name_Var (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_Same_Name_Var
AS BEGIN
   FUNCTION PF_Same_Name_Var
   RETURNS VARCHAR(100);
   PROCEDURE PP_Same_Name_Var; 
END; 

/* Тело пакета */
RECREATE PACKAGE BODY Pack_Same_Name_Var
AS BEGIN
   FUNCTION PF_Same_Name_Var
   RETURNS VARCHAR(100)
   AS
    /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
    /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
    DECLARE summa VARCHAR(100) = '';
     DECLARE i VARCHAR(15);
     DECLARE j VARCHAR(15);
     DECLARE i_FOR1 INTEGER;
     DECLARE j_FOR1 VARCHAR(15);
   BEGIN
    INSERT INTO VEC_Pack_Same_Name_Var_PF_Same_Name_Var(VAL) VALUES ('John');
    INSERT INTO VEC_Pack_Same_Name_Var_PF_Same_Name_Var(VAL) VALUES ('Mary');
    INSERT INTO VEC_Pack_Same_Name_Var_PF_Same_Name_Var(VAL) VALUES ('Alberto');
    INSERT INTO VEC_Pack_Same_Name_Var_PF_Same_Name_Var(VAL) VALUES ('Juanita');
    FOR SELECT ID, VAL FROM VEC_Pack_Same_Name_Var_PF_Same_Name_Var
    ORDER BY ID ASC
    INTO :i_FOR1, :j_FOR1
    DO
    BEGIN
      summa = :summa || j_FOR1; 
    END
    i = 'Jon';
    summa = :summa || i;
    RETURN summa;
   END

   PROCEDURE PP_Same_Name_Var
   AS
     /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
     /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa VARCHAR(100) = '';
     DECLARE i VARCHAR(15);
     DECLARE j VARCHAR(15);
     DECLARE i_FOR1 INTEGER;
     DECLARE j_FOR1 VARCHAR(15);
   BEGIN
     INSERT INTO VEC_Pack_Same_Name_Var_PP_Same_Name_Var(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_Same_Name_Var_PP_Same_Name_Var(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_Same_Name_Var_PP_Same_Name_Var(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_Same_Name_Var_PP_Same_Name_Var(VAL) VALUES ('Juanita');
     FOR SELECT ID, VAL FROM VEC_Pack_Same_Name_Var_PP_Same_Name_Var
     ORDER BY ID ASC
     INTO :i_FOR1, :j_FOR1
     DO
     BEGIN
       summa = :summa || j_FOR1; 
     END
     i = 'Jon';
     summa = :summa || i;
   END  
END; 

/* Триггер DML */
CREATE GLOBAL TEMPORARY TABLE VEC_T_Same_Name_Var (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER TRIGGER T_Same_Name_Var
  AFTER INSERT 
  ON students
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
  /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa VARCHAR(100) = '';
  DECLARE i VARCHAR(15);
  DECLARE j VARCHAR(15);
  DECLARE i_FOR1 INTEGER;
  DECLARE j_FOR1 VARCHAR(15);
BEGIN
  INSERT INTO VEC_T_Same_Name_Var(VAL) VALUES ('John');
  INSERT INTO VEC_T_Same_Name_Var(VAL) VALUES ('Mary');
  INSERT INTO VEC_T_Same_Name_Var(VAL) VALUES ('Alberto');
  INSERT INTO VEC_T_Same_Name_Var(VAL) VALUES ('Juanita');
  FOR SELECT ID, VAL FROM VEC_T_Same_Name_Var
  ORDER BY ID ASC
  INTO :i_FOR1, :j_FOR1
  DO
  BEGIN
    summa = :summa || j_FOR1; 
  END
  i = 'Jon';
  summa = :summa || i;
END;

/* Анонимный блок */
CREATE GLOBAL TEMPORARY TABLE VEC_Varray_1 (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

EXECUTE BLOCK 
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
  /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
  DECLARE summa VARCHAR(100) = '';
  DECLARE i VARCHAR(15);
  DECLARE j VARCHAR(15);
  DECLARE i_FOR1 INTEGER;
  DECLARE j_FOR1 VARCHAR(15);
BEGIN
  INSERT INTO VEC_Varray_1(VAL) VALUES ('John');
  INSERT INTO VEC_Varray_1(VAL) VALUES ('Mary');
  INSERT INTO VEC_Varray_1(VAL) VALUES ('Alberto');
  INSERT INTO VEC_Varray_1(VAL) VALUES ('Juanita');
  FOR SELECT ID, VAL FROM VEC_Varray_1
  ORDER BY ID ASC
  INTO :i_FOR1, :j_FOR1
  DO
  BEGIN
    summa = :summa || j_FOR1; 
  END
  i = 'Jon';
  j = 'Rose';
  summa = :summa || i || j;
END;
