CREATE GLOBAL TEMPORARY TABLE VEC_AssArr_1 (
    K INTEGER,
    VAL INTEGER,
    CONSTRAINT PK_VEC_AssArr_1 PRIMARY KEY (K)
);

EXECUTE BLOCK
AS
   /* TYPE intvec_t IS TABLE OF PLS_INTEGER INDEX BY PLS_INTEGER; */
   /* vec intvec_t := intvec_t(3 => 10, 1 => 11, 100 => 34); */
   DECLARE summa NUMERIC(5,1) = 0;
   DECLARE n_FOR1 INTEGER;
   DECLARE m_FOR1 NUMERIC(5,1);
BEGIN
   UPDATE OR INSERT INTO VEC_AssArr_1 VALUES (3, 10);
   UPDATE OR INSERT INTO VEC_AssArr_1 VALUES (1, 11);
   UPDATE OR INSERT INTO VEC_AssArr_1 VALUES (100, 34);
   FOR SELECT K, VAL FROM VEC_AssArr_1
   ORDER BY K ASC
   INTO :n_FOR1, :m_FOR1
   DO
   BEGIN
     summa = summa + m_FOR1;
   END
END;