EXECUTE BLOCK
    AS
    DECLARE TYPE EMPLOYEE_RECORD (
        EMP_ID NUMERIC(34, 8),
    	EMP_NAME VARCHAR(50),
   	    EMP_SALARY NUMERIC(34, 8)
    );

    DECLARE EMP EMPLOYEE_RECORD;
BEGIN
    EMP.EMP_ID = 1001;
    EMP.EMP_NAME = 'JOHN DOE';
    EMP.EMP_SALARY = 50000;
END;