CREATE PACKAGE PKG IS
    TYPE EMPLOYEE_RECORD IS RECORD (
        EMP_ID NUMBER,
        EMP_NAME VARCHAR2(50),
        EMP_SALARY NUMBER
    );
END;

DECLARE
    EMP PKG.EMPLOYEE_RECORD := PKG.EMPLOYEE_RECORD(1000, 'ALEX', 5000);
BEGIN
    NULL;
END;