EXECUTE BLOCK
    AS
    DECLARE TYPE EMPLOYEE_RECORD (
        EMP_ID NUMERIC(34, 8),
    	EMP_NAME VARCHAR(50),
   	    EMP_SALARY NUMERIC(34, 8)
    );
    DECLARE TYPE EMPLOYEE_RECORD_2 (
            FIELD EMPLOYEE_RECORD
    );
    DECLARE EMP EMPLOYEE_RECORD;
BEGIN

END;