EXECUTE BLOCK
    AS
DECLARE TYPE EMPLOYEE_RECORD (
        EMP_ID NUMERIC(34, 8),
    	EMP_NAME VARCHAR(50),
   	    EMP_SALARY NUMERIC(34, 8)
    );

    DECLARE EMP EMPLOYEE_RECORD = ROW(1000, 'alex', 5000);
BEGIN

END;