EXECUTE BLOCK
    AS
    DECLARE TYPE EMPREC (
        LAST_NAME VARCHAR(10),
        JOB_TITLE VARCHAR(9),
        SALARY    NUMERIC(7,2));
    DECLARE PROCEDURE RAISE_SALARY (EMP_INFO EMPREC)
		AS
    BEGIN

    END
BEGIN

END;