EXECUTE BLOCK
    AS
    DECLARE TYPE NAME_REC (
        FIRST  NUMERIC(34, 8),
        LAST   NUMERIC(34, 8)
  );

    DECLARE TYPE CONTACT (
        NAME  NAME_REC,
        FIELD VARCHAR(100)
  );
   DECLARE FRIEND CONTACT;
BEGIN
    NULL;
END;