DECLARE
    TYPE EMPREC IS RECORD (
        EMP_ID NUMBER(4),
        LAST_NAME VARCHAR2(10),
        DEPT_NUM NUMBER(2),
        JOB_TITLE VARCHAR2(9),
        SALARY NUMBER(7,2));
    FUNCTION NTH_HIGHEST_SALARY (N INTEGER) RETURN EMPREC
        IS
    BEGIN
        NULL;
    END;
BEGIN
    NULL;
END;