EXECUTE BLOCK
    AS
    DECLARE TYPE EMPREC (
        EMP_ID NUMERIC(4),
        LAST_NAME VARCHAR(10),
        DEPT_NUM NUMERIC(2),
        JOB_TITLE VARCHAR(9),
        SALARY NUMERIC(7,2));
    DECLARE FUNCTION NTH_HIGHEST_SALARY (N INTEGER) RETURNS EMPREC
        AS
    BEGIN

    END
BEGIN

END;