DECLARE
    TYPE EMPREC IS RECORD (
        LAST_NAME VARCHAR2(10),
        JOB_TITLE VARCHAR2(9),
        SALARY    NUMBER(7,2));
    PROCEDURE RAISE_SALARY (EMP_INFO EMPREC)
        IS
    BEGIN
        NULL;
    END;
BEGIN
    NULL;
END;