EXECUTE BLOCK
    AS

    DECLARE VARIABLE DEPT_INFO TYPE OF TABLE COUNTRY;
BEGIN

    DELETE FROM COUNTRY  WHERE COUNTRY = 'COUNTRY_NAME' RETURNING COUNTRY_NAME, COUNTRY_CURRENCY INTO DEPT_INFO;
END;