CREATE GLOBAL TEMPORARY TABLE VEC_F_For_With_When (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE FUNCTION F_For_With_When
RETURNS VARCHAR(100)
AS
   /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
   /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa INTEGER = 0;
   DECLARE i_FOR1 INTEGER;
   DECLARE j_FOR1 VARCHAR(15);
BEGIN
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('John');
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('Mary');
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('Alberto');
   INSERT INTO VEC_F_For_With_When(VAL) VALUES ('Juanita');
   FOR SELECT ID, VAL FROM VEC_F_For_With_When
   ORDER BY ID ASC
   INTO :i_FOR1, :j_FOR1
   DO
   BEGIN
     IF (NOT(i_FOR1 != 2)) THEN CONTINUE;
     summa = :summa + i_FOR1; 
   END
END;