CREATE PROCEDURE GET_BAL(ACC_NO NUMERIC(34, 8))
RETURNS (RET_VAL BOOLEAN,
    ACC_NO_OUT NUMERIC(34, 8))
    SQL SECURITY DEFINER
AS
BEGIN

    RET_VAL = TRUE;
    ACC_NO_OUT = ACC_NO;
    SUSPEND;
    EXIT;
END;