CREATE GLOBAL TEMPORARY TABLE VEC_P_From_Varray (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE PROCEDURE P_From_Varray
AS
  /* TYPE varray_t IS VARRAY(4) OF VARCHAR2(15); */
   /* vec varray_t := varray_t('John', 'Mary', 'Alberto', 'Juanita'); */
   DECLARE summa VARCHAR(100) = '';
   DECLARE i_FOR1 VARCHAR(15);
BEGIN
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('John');
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('Mary');
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('Alberto');
   INSERT INTO VEC_P_From_Varray(VAL) VALUES ('Juanita');
   FOR SELECT VAL FROM VEC_P_From_Varray
   ORDER BY ID ASC
   INTO :i_FOR1
   DO
   BEGIN
     summa = :summa || i_FOR1; 
   END
END;