CREATE OR REPLACE FUNCTION CALL_F
RETURN BOOLEAN
AUTHID DEFINER
IS
    VALUE_OUT NUMBER;
    STMT VARCHAR2(50);
BEGIN
    VALUE_OUT := 0;
    STMT := 'BEGIN OUT_P(:A); END;';
    EXECUTE IMMEDIATE STMT USING IN OUT VALUE_OUT;
    RETURN TRUE;
END;