CREATE OR REPLACE TRIGGER CALL_TR
AFTER INSERT
ON COUNTRY
FOR EACH ROW
DECLARE
    VALUE_OUT NUMBER;
    STMT VARCHAR2(50);
BEGIN
    VALUE_OUT := 0;
    STMT := 'BEGIN OUT_P(:A); END;';
    EXECUTE IMMEDIATE STMT USING OUT VALUE_OUT;
END;