CREATE GLOBAL TEMPORARY TABLE VEC_Pack_For_With_When_PF_For_With_When (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE GLOBAL TEMPORARY TABLE VEC_Pack_For_With_When_PP_For_With_When (
    ID  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VAL VARCHAR(15)
);

CREATE OR ALTER PACKAGE Pack_For_With_When
AS BEGIN
   FUNCTION PF_For_With_When
   RETURNS VARCHAR(100);
   PROCEDURE PP_For_With_When; 
END; 

RECREATE PACKAGE BODY Pack_For_With_When
AS BEGIN
   FUNCTION PF_For_With_When
   RETURNS VARCHAR(100)
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
   BEGIN
     INSERT INTO VEC_Pack_For_With_When_PF_For_With_When(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_For_With_When_PF_For_With_When(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_For_With_When_PF_For_With_When(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_For_With_When_PF_For_With_When(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC_Pack_For_With_When_PF_For_With_When
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       IF (NOT(i_FOR1 != 2)) THEN CONTINUE;
       summa = :summa + i_FOR1; 
     END
     RETURN summa;
   END

   PROCEDURE PP_For_With_When
   AS
     /* TYPE nesttabl_t IS TABLE OF VARCHAR2(15); */
     /* vec nesttabl_t := nesttabl_t('John', 'Mary', 'Alberto', 'Juanita'); */
     DECLARE summa INTEGER = 0;
     DECLARE i_FOR1 INTEGER;
   BEGIN
     INSERT INTO VEC_Pack_For_With_When_PP_For_With_When(VAL) VALUES ('John');
     INSERT INTO VEC_Pack_For_With_When_PP_For_With_When(VAL) VALUES ('Mary');
     INSERT INTO VEC_Pack_For_With_When_PP_For_With_When(VAL) VALUES ('Alberto');
     INSERT INTO VEC_Pack_For_With_When_PP_For_With_When(VAL) VALUES ('Juanita');
     FOR SELECT ID FROM VEC_Pack_For_With_When_PP_For_With_When
     ORDER BY ID ASC
     INTO :i_FOR1
     DO
     BEGIN
       IF (NOT(i_FOR1 != 2)) THEN CONTINUE;
       summa = :summa + i_FOR1; 
     END
   END  
END;  